/*
 * dsh-jail-run — FreeBSD sandbox runner for deepseek-harness (dsh).
 *
 * SECURITY MODEL (read before touching this file):
 *   This program is installed setuid-root (mode 4755, owner root:wheel). Any
 *   local user who can execute it can therefore create FreeBSD jails. Two
 *   properties keep that privilege contained:
 *
 *   1. The command is executed INSIDE the jail as the ORIGINAL (real) caller
 *      uid/gid — never as root. The setuid bit is only used to (a) create the
 *      jail and (b) mount the read-only system view; both happen before
 *      privileges are dropped via setuid/setgid in the child.
 *
 *   2. The workspace that gets mounted read-write is validated: it must be an
 *      absolute path, resolve via realpath with no ".." components, and is the
 *      ONLY writable host directory exposed. Everything else is a read-only
 *      nullfs mount or a fresh tmpfs. The jail has no network by default.
 *
 *   The binary MUST be root-owned and NOT group/world writable, and live in a
 *   directory (/usr/local/sbin) that non-root users cannot rename/replace.
 *   Installation is an explicit admin action (see FREEBSD.md). There is no
 *   silent privilege escalation: without the setuid bit this program can only
 *   create jails when already root, and the harness never grants root.
 *
 * Behaviour:
 *   dsh-jail-run --workspace <hostRoot> --mode <read-only|workspace-write>
 *                [--session <id>] [--network] -- <command...>
 *   Creates an ephemeral jail rooted at a fresh dir, mounts the host system
 *   (ro) + workspace (ro/rw) + devfs (restricted) + tmpfs /tmp, attaches,
 *   drops privileges to the caller, chdir's to the in-jail workspace
 *   (/workspace), and exec's <command>. The jail is ephemeral (persist=1 so we
 *   can clean it up; removed on normal exit). Parent unmounts + removes the
 *   jail on child exit; best-effort on signals.
 *
 * Exit codes:
 *   0-125  propagated command exit (128+signo if killed by signal)
 *   125    runner failure (validation / mount / jail creation) — matches the
 *          harness's RUNNER_FAILURE_RULES allowedExitCodes for this backend.
 *   126    usage error.
 */

#ifndef MAXPATHLEN
#define MAXPATHLEN 1024
#endif

#include <sys/param.h>
#include <sys/types.h>
#include <sys/jail.h>   /* legacy struct jail (needs MAXPATHLEN) + jail_set/attach/remove */
#include <jail.h>       /* jailparam_init/set/free + struct jailparam */
#include <sys/mount.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <sys/wait.h>
#include <signal.h>

#include <errno.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>

#define DENY_RC 125
#define USAGE_RC 126

#define JAIL_BIN "/usr/local/sbin/dsh-jail-run"
/* In-jail path the workspace is mounted at; the command's cwd lands here. */
#define IN_JAIL_WORKSPACE "/workspace"
/* Read-only system directories exposed inside the jail.
 *
 * IMPORTANT (FreeBSD nullfs gotcha): you cannot nullfs-mount one filesystem
 * onto a path that lives UNDER another nullfs mount — it fails with
 * "Resource deadlock avoided" (EDEADLK). So we must NOT mount /usr as a single
 * nullfs AND also mount /usr/local (which lives under /usr). Instead /usr is
 * left as a plain (empty) directory and we mount the specific /usr subdirs we
 * need, plus /usr/local (a separate dataset) — each as its own nullfs whose
 * mountpoint does NOT sit under another nullfs mount. None of these nest, so
 * nullfs stays happy. /usr/local is where the ports `bash` (and its libs) live. */
static const char *SYS_RO_MOUNTS[] = {
  "/bin", "/sbin", "/lib", "/libexec", "/etc",
  "/usr/bin", "/usr/sbin", "/usr/lib", "/usr/libexec",
  "/usr/share", "/usr/include", "/usr/libdata",
  "/usr/local",
  NULL
};

static volatile sig_atomic_t g_child = 0;
static char *g_root = NULL;
static char *g_jailname = NULL;
static int g_jid = -1;

static void cleanup(void);  /* forward decl (used by runner_fail) */
static void mkdirp(const char *path);  /* forward decl (used by do_mount) */

static void die(int rc, const char *fmt, ...) {
  va_list ap;
  va_start(ap, fmt);
  vfprintf(stderr, fmt, ap);
  va_end(ap);
  fputc('\n', stderr);
  exit(rc);
}

static void runner_fail(const char *fmt, ...) {
  va_list ap;
  /* Runner diagnostics are tagged so the harness can classify them as a
   * runner failure (command never ran) rather than a sandbox denial. */
  fprintf(stderr, "dsh-jail-run: ");
  va_start(ap, fmt);
  vfprintf(stderr, fmt, ap);
  va_end(ap);
  fputc('\n', stderr);
  /* Tear down any partial jail/mounts so a failed run never leaks. */
  cleanup();
  exit(DENY_RC);
}

/* Best-effort resource limits via rctl (controlled strings only — the jail
 * name is generated by us, never user input). Non-fatal: if racct is disabled
 * or a limit cannot be applied we only warn. */
static void apply_rctl(const char *name) {
  char cmd[256];
  snprintf(cmd, sizeof(cmd), "rctl -a 'jail:%s:maxproc:deny=256' 2>/dev/null", name);
  system(cmd);
  snprintf(cmd, sizeof(cmd), "rctl -a 'jail:%s:pcpu:deny=90' 2>/dev/null", name);
  system(cmd);
}

static void release_rctl(const char *name) {
  char cmd[256];
  snprintf(cmd, sizeof(cmd), "rctl -r 'jail:%s:maxproc' 2>/dev/null", name);
  system(cmd);
  snprintf(cmd, sizeof(cmd), "rctl -r 'jail:%s:pcpu' 2>/dev/null", name);
  system(cmd);
}

static void join(char *out, size_t n, const char *suffix) {
  snprintf(out, n, "%s%s", g_root, suffix);
}

/* Mount via /sbin/mount using execl (no shell — the arguments are validated
 * paths we control, so there is no command-injection surface). We fork so the
 * privileged parent keeps its root context for later mounts/jail creation. */
static void run_mount(const char *type, const char *src, const char *dst, int ro) {
  pid_t p = fork();
  if (p == 0) {
    if (src == NULL) /* source-less fs (tmpfs): pass the type as the source node */
      execl("/sbin/mount", "mount", "-t", type, "-o", ro ? "ro" : "rw", type, dst, (char *)NULL);
    else if (ro) execl("/sbin/mount", "mount", "-t", type, "-o", "ro", src, dst, (char *)NULL);
    else execl("/sbin/mount", "mount", "-t", type, "-o", "rw", src, dst, (char *)NULL);
    _exit(127);
  }
  int st;
  while (waitpid(p, &st, 0) < 0 && errno == EINTR) { /* retry */ }
  if (!(WIFEXITED(st) && WEXITSTATUS(st) == 0)) {
    runner_fail("mount %s (%s) at %s failed", type, src == NULL ? "" : src, dst);
  }
}

static void run_unmount(const char *dst) {
  pid_t p = fork();
  if (p == 0) { execl("/sbin/umount", "umount", dst, (char *)NULL); _exit(127); }
  int st;
  while (waitpid(p, &st, 0) < 0 && errno == EINTR) { /* retry */ }
  /* Best-effort; ignore failures (another pass or manual cleanup may clear). */
}

static void do_mount(const char *type, const char *src, const char *dst, int ro) {
  mkdirp(dst);  /* create intermediate dirs (e.g. <root>/usr/bin) */
  run_mount(type, src, dst, ro);
}

/* Mount a restricted devfs (ruleset 4 = jail-appropriate devices only) at the
 * jail's /dev. Done by hand (see comment at the jailparam_set call site). */
static void do_mount_devfs(const char *dst) {
  mkdirp(dst);
  pid_t p = fork();
  if (p == 0) {
    execl("/sbin/mount", "mount", "-t", "devfs", "-o", "ruleset=4", "devfs", dst, (char *)NULL);
    _exit(127);
  }
  int st;
  while (waitpid(p, &st, 0) < 0 && errno == EINTR) { /* retry */ }
  if (!(WIFEXITED(st) && WEXITSTATUS(st) == 0)) {
    runner_fail("mount devfs at %s failed", dst);
  }
}

/* Recursive mkdir (creates intermediate components). Paths are generated by us
 * (jail-root + a known suffix), so we tolerate EEXIST and only surface real
 * failures. */
static void mkdirp(const char *path) {
  char tmp[PATH_MAX];
  snprintf(tmp, sizeof(tmp), "%s", path);
  for (char *p = tmp + 1; *p != '\0'; p++) {
    if (*p == '/') {
      *p = '\0';
      mkdir(tmp, 0755);  /* ignore EEXIST */
      *p = '/';
    }
  }
  mkdir(tmp, 0755);
}

/* Forward signals to the child so the harness can terminate a session. */
static void on_signal(int sig) {
  if (g_child > 0) kill(g_child, sig);
}

static void cleanup(void) {
  if (g_jid > 0) {
    release_rctl(g_jailname);
    jail_remove(g_jid);   /* removes the jail (and any kernel-managed mounts) */
    g_jid = -1;
  }
  if (g_root != NULL) {
    char p[PATH_MAX];
    for (int k = 0; SYS_RO_MOUNTS[k] != NULL; k++) {
      join(p, sizeof(p), SYS_RO_MOUNTS[k]);
      run_unmount(p);
    }
    join(p, sizeof(p), "/workspace"); run_unmount(p);
    join(p, sizeof(p), "/tmp"); run_unmount(p);
    join(p, sizeof(p), "/dev"); run_unmount(p);
    join(p, sizeof(p), "/var/run/ld-elf.so.hints"); run_unmount(p);
    /* The jail root tree only contains mounts + dirs we created; remove it
     * wholesale. We are still in the HOST context here (only the child is
     * jailed), so /bin/rm on the host is always available. */
    pid_t rp = fork();
    if (rp == 0) { execl("/bin/rm", "rm", "-rf", g_root, (char *)NULL); _exit(127); }
    int st; while (waitpid(rp, &st, 0) < 0 && errno == EINTR) { /* retry */ }
  }
}

int main(int argc, char **argv) {
  /* Capture the REAL caller identity BEFORE any setuid confusion. With the
   * setuid bit, getuid() is the invoking user (e.g. workbuddy) and geteuid()
   * is 0 (root). We keep the caller's uid/gid to drop into after attach. */
  uid_t ruid = getuid();
  gid_t rgid = getgid();

  const char *workspace = NULL;
  const char *mode = NULL;
  int want_network = 0;

  int i = 1;
  for (; i < argc; i++) {
    if (strcmp(argv[i], "--") == 0) { i++; break; }
    if (strcmp(argv[i], "--workspace") == 0 && i + 1 < argc) workspace = argv[++i];
    else if (strcmp(argv[i], "--mode") == 0 && i + 1 < argc) mode = argv[++i];
    else if (strcmp(argv[i], "--session") == 0 && i + 1 < argc) (void)argv[++i]; /* reserved */
    else if (strcmp(argv[i], "--network") == 0) want_network = 1;
    else runner_fail("unknown/incomplete argument: %s", argv[i]);
  }
  if (workspace == NULL || mode == NULL) {
    die(USAGE_RC, "usage: %s --workspace <root> --mode <read-only|workspace-write> [--session <id>] [--network] -- <command...>", JAIL_BIN);
  }
  if (strcmp(mode, "read-only") != 0 && strcmp(mode, "workspace-write") != 0) {
    runner_fail("invalid --mode %s (want read-only|workspace-write)", mode);
  }
  if (i >= argc) runner_fail("no command supplied after --");
  char **command = &argv[i];

  /* Validate the workspace: absolute, realpath-resolved, no traversal. */
  if (workspace[0] != '/') runner_fail("workspace must be absolute: %s", workspace);
  char resolved[PATH_MAX];
  if (realpath(workspace, resolved) == NULL) {
    runner_fail("realpath %s: %s", workspace, strerror(errno));
  }
  if (strcmp(resolved, "/") == 0) runner_fail("refusing to jail the host root");

  /* Network is OFF by default; an operator may opt in via --network or the
   * DSH_JAIL_NETWORK environment variable. */
  if (!want_network && getenv("DSH_JAIL_NETWORK") != NULL) want_network = 1;

  /* Choose a root-owned, mode-0700 base for the jail root. */
  const char *bases[] = {"/var/run/dsh-jails", "/tmp/dsh-jails", NULL};
  const char *base = NULL;
  for (int b = 0; bases[b] != NULL; b++) {
    if (mkdir(bases[b], 0700) == 0 || errno == EEXIST) { base = bases[b]; break; }
  }
  if (base == NULL) runner_fail("cannot create a jail base directory");

  char template[PATH_MAX];
  snprintf(template, sizeof(template), "%s/dsh-jail.XXXXXX", base);
  g_root = mkdtemp(template);
  if (g_root == NULL) runner_fail("mkdtemp: %s", strerror(errno));
  /* The jail root must be traversable by the (dropped) sandbox user, otherwise
   * chdir("/workspace") fails with EACCES once we are no longer root. We give
   * "other" execute-only (--x) so the sandboxed uid can walk through to its
   * mounts but cannot list the root directory's contents. */
  chmod(g_root, 0711);

  /* Jail name (alphanumeric only — used in rctl/system strings). */
  char jn[64];
  unsigned long r = (unsigned long)getpid() ^ (unsigned long)time(NULL);
  snprintf(jn, sizeof(jn), "dsh%lu", r & 0xffffffffUL);
  g_jailname = jn;

  /* Create the in-jail directory layout. */
  for (int k = 0; SYS_RO_MOUNTS[k] != NULL; k++) {
    char d[PATH_MAX];
    join(d, sizeof(d), SYS_RO_MOUNTS[k]);
    mkdirp(d);
  }
  char devp[PATH_MAX]; join(devp, sizeof(devp), "/dev"); mkdirp(devp);
  char wsp[PATH_MAX]; join(wsp, sizeof(wsp), "/workspace"); mkdirp(wsp);
  char tmp[PATH_MAX]; join(tmp, sizeof(tmp), "/tmp"); mkdirp(tmp);

  /* The dynamic linker relies on the ldconfig hints (/var/run/ld-elf.so.hints)
   * to know where to search for shared libraries — notably /usr/local/lib,
   * where the ports `bash` and many tools keep their libs. The jail has no
   * such file by default, so we nullfs-mount the host's (read-only) hints in.
   * Target is g_root/var/run/ld-elf.so.hints, which sits under a plain /var
   * dir (not under any nullfs mount), so no nesting/deadlock. */
  char hintdir[PATH_MAX]; join(hintdir, sizeof(hintdir), "/var/run");
  mkdirp(hintdir);
  char hintfile[PATH_MAX]; join(hintfile, sizeof(hintfile), "/var/run/ld-elf.so.hints");
  int hf = open(hintfile, O_CREAT | O_RDONLY, 0444);
  if (hf >= 0) close(hf);
  do_mount("nullfs", "/var/run/ld-elf.so.hints", hintfile, 1);

  /* Read-only system view. */
  for (int k = 0; SYS_RO_MOUNTS[k] != NULL; k++) {
    char dst[PATH_MAX];
    join(dst, sizeof(dst), SYS_RO_MOUNTS[k]);
    do_mount("nullfs", SYS_RO_MOUNTS[k], dst, 1);
  }
  /* Workspace: rw for workspace-write, ro for read-only. */
  do_mount("nullfs", resolved, wsp, strcmp(mode, "read-only") == 0 ? 1 : 0);
  /* Fresh tmpfs for /tmp. */
  do_mount("tmpfs", NULL, tmp, 0);
  /* The tmpfs mountpoint is created 0755 root-owned; make it world-writable and
   * sticky (like a real /tmp) so the (privilege-dropped) sandbox user can
   * actually use it. Done while still root, before the child drops privileges. */
  if (chmod(tmp, 01777) != 0) runner_fail("chmod /tmp: %s", strerror(errno));
  /* devfs (restricted ruleset) — mounted manually because the jailparam
   * "mount.devfs" import fails with ENOENT on this box and a failed import
   * leaves jp_value NULL, which makes jailparam_set segfault. */
  do_mount_devfs(devp);

  /* Create the jail (persist=1 so we can remove it deterministically).
   * We deliberately do NOT pass mount.devfs/devfs_ruleset jailparams for the
   * reason above; devfs is mounted by hand instead. */
  struct jailparam jp[7];
  memset(jp, 0, sizeof(jp));
  jailparam_init(&jp[0], "name"); jailparam_import(&jp[0], jn);
  jailparam_init(&jp[1], "path"); jailparam_import(&jp[1], g_root);
  jailparam_init(&jp[2], "host.hostname"); jailparam_import(&jp[2], "dsh-jail");
  jailparam_init(&jp[3], "ip4"); jailparam_import(&jp[3], want_network ? "inherit" : "disable");
  jailparam_init(&jp[4], "ip6"); jailparam_import(&jp[4], want_network ? "inherit" : "disable");
  jailparam_init(&jp[5], "enforce_statfs"); jailparam_import(&jp[5], "2");
  jailparam_init(&jp[6], "persist"); jailparam_import(&jp[6], "1");

  g_jid = jailparam_set(jp, 7, JAIL_CREATE);
  for (int k = 0; k < 7; k++) jailparam_free(&jp[k], 1);
  if (g_jid < 0) runner_fail("jailparam_set: %s", strerror(errno));

  apply_rctl(jn);

  /* Forward termination signals to the child. */
  signal(SIGTERM, on_signal);
  signal(SIGINT, on_signal);
  signal(SIGABRT, on_signal);

  pid_t pid = fork();
  if (pid < 0) runner_fail("fork: %s", strerror(errno));

  if (pid == 0) {
    /* Child: enter the jail, drop privileges, run the command. */
    if (jail_attach(g_jid) != 0) {
      fprintf(stderr, "dsh-jail-run: jail_attach: %s\n", strerror(errno));
      _exit(DENY_RC);
    }
    /* Drop to the original caller (never root). */
    if (setgroups(1, &rgid) != 0 ||
        setgid(rgid) != 0 ||
        setuid(ruid) != 0) {
      fprintf(stderr, "dsh-jail-run: privilege drop failed: %s\n", strerror(errno));
      _exit(DENY_RC);
    }
    /* Land in the workspace view; give the sandboxed process a sane HOME. */
    if (chdir(IN_JAIL_WORKSPACE) != 0) {
      fprintf(stderr, "dsh-jail-run: chdir %s: %s\n", IN_JAIL_WORKSPACE, strerror(errno));
      _exit(DENY_RC);
    }
    setenv("HOME", IN_JAIL_WORKSPACE, 1);
    execvp(command[0], command);
    fprintf(stderr, "dsh-jail-run: exec %s: %s\n", command[0], strerror(errno));
    _exit(127);
  }

  /* Parent: wait for the command, then clean up. */
  g_child = pid;
  int status = 0;
  while (waitpid(pid, &status, 0) < 0 && errno == EINTR) { /* retry */ }
  g_child = 0;

  cleanup();

  if (WIFEXITED(status)) exit(WEXITSTATUS(status));
  if (WIFSIGNALED(status)) exit(128 + WTERMSIG(status));
  exit(DENY_RC);
}
