"""
lightpub 包索引 (自动生成)

包总数: 109
数据源: C:/dumatework/lightpub/packages/
生成工具: tools/gen_lightpub_index.py

此文件由脚本自动生成，请勿手动编辑。
如需更新索引，运行: python tools/gen_lightpub_index.py
"""

# 每个包的元数据
PACKAGES = {
    '2D绘图': {
        "version": '1.0.0',
        "description": '2D绘图库：画布、路径、形状、颜色、变换、SVG导出',
        "category": 'dev',
        "keywords": ['2D绘图', '画布', '路径', '形状', 'SVG', '颜色'],
        "dependencies": [],
        "functions": ['创建颜色', '颜色转为十六进制', '颜色变亮', '颜色变暗', '颜色混合', '创建画布', '画布设置画笔', '画布设置画刷', '画布设置字体', '画布清除', '画布保存状态', '画布恢复状态', '画布绘制矩形', '画布填充矩形', '画布绘制圆角矩形', '画布填充圆角矩形', '画布绘制椭圆', '画布填充椭圆', '画布绘制圆', '画布填充圆', '画布绘制直线', '画布绘制多段线', '画布填充多边形', '画布绘制曲线', '画布绘制弧线', '画布绘制文本', '画布绘制文本居中', '画布绘制图像', '创建路径：', '路径移动到', '路径画线到', '路径画曲线到', '路径画二次曲线到', '路径画弧线到', '路径闭合', '画布绘制路径', '画布填充路径', '画布平移', '画布缩放', '画布旋转', '画布倾斜', '画布重置变换', '画布变换点', '画布获取像素', '画布设置像素', '画布裁剪到矩形', '创建线性渐变', '创建径向渐变', '画布导出SVG', '画布导出SVG美化', '画布保存SVG', '颜色转SVG', '变换转SVG', '元素转SVG', '整数转十六进制', '数值转字符串', '向下取整', '取最小值', '取最大值', '余弦', '正弦', '重复字符串', '列表移除最后', '文件写入'],
        "function_count": 64,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/2D绘图',
    },
    'Actor模型': {
        "version": '1.0.0',
        "description": 'Actor模型：Actor创建、消息传递、监督树、错误处理、路由',
        "category": 'dev',
        "keywords": ['Actor', '消息传递', '监督树', '并发', '路由'],
        "dependencies": [],
        "functions": ['生成唯一标识', '当前时间戳', '创建执行体系统', '系统创建执行体', '系统停止执行体', '系统暂停执行体', '系统恢复执行体', '系统重启执行体', '系统发送消息', '系统发送消息异步', '系统广播消息', '系统处理消息', '系统处理所有消息', '系统运行', '系统停止', '系统获取执行体', '系统获取所有执行体', '系统获取统计', '系统获取日志', '创建监督策略', '监督策略添加错误处理', '系统处理执行体失败', '系统升级失败', '创建路由策略', '系统创建路由执行体', '路由策略选择目标', '创建执行体上下文', '上下文创建子执行体', '上下文停止子执行体', '上下文发送给父执行体', '上下文发送给子执行体', '上下文获取数据', '上下文设置数据', '上下文自我引用', '创建执行体引用'],
        "function_count": 35,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/Actor模型',
    },
    'AI推理': {
        "version": '1.0.0',
        "description": 'AI推理库：模型加载、推理接口、数据预处理、后处理、批量推理',
        "category": 'dev',
        "keywords": ['AI推理', '模型', '预处理', '后处理', '批量推理'],
        "dependencies": [],
        "functions": ['createModel', 'mdl_load', 'mdl_unload', 'mdl_isLoaded', 'mdl_getInputShape', 'mdl_getOutputShape', 'mdl_setBatchSize', 'mdl_setThreads', 'mdl_infer', 'mdl_batchInfer', 'mdl_inferAsync', 'createTensor', 'tensor_getData', 'tensor_shape', 'tensor_reshape', 'tensor_transpose', 'tensor_slice', 'tensor_add', 'tensor_mul', 'tensor_normalize', 'createPreprocessConfig', 'preprocessImage', 'preprocessAugment', 'preprocessClassify', 'preprocessDetect', 'postprocessClassify', 'postprocessDetect', 'postprocessSegment', '后处理NMS', '计算softmax', '计算argmax', '均值池化', '最大池化', '图像转张量', '张量转图像', '标准化数据', '中心化数据', '缩放数据', '填充数据', '裁剪数据', 'createDataAugment', 'aug_enableRandCrop', 'aug_enableRandHFlip', 'aug_apply', '最大值', '最小值'],
        "function_count": 46,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/AI推理',
    },
    'API文档': {
        "version": '1.0.0',
        "description": 'OpenAPI3.0/Swagger自动生成：路由扫描、参数解析、响应定义、交互式文档',
        "category": 'dev',
        "keywords": ['API', '文档', 'OpenAPI', 'Swagger', '路由'],
        "dependencies": [],
        "functions": ['范围', '创建API文档', 'API文档添加服务器', 'API文档添加标签', 'API文档添加路由', 'API文档添加模型', 'API文档从路由列表生成', '生成OpenAPI3', '生成OpenAPI3美化', '生成Swagger2', '生成HTML', '生成精简版', '导出到文件'],
        "function_count": 13,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/API文档',
    },
    'CSV': {
        "version": '1.0.0',
        "description": 'CSV/TSV读写、流式解析、类型推断、方言自动检测',
        "category": 'dev',
        "keywords": ['CSV', 'TSV', '表格', '数据', '解析'],
        "dependencies": [],
        "functions": ['inferCellType', 'convertCellValue', 'parseCSV', 'parseCSVFile', 'parseCSVStream', 'autoDetectDelimiter', 'toDictList', 'to2DArray', 'getColumn', 'serializeCSV', 'serializeCSVFile'],
        "function_count": 11,
        "ffi_count": 2,
        "has_source": True,
        "priority": 'P0',
        "stdlib_equivalent": 'CSV读写器',
        "note": '已有 Python 实现，桥接到 stdlib',
        "path": 'packages/CSV',
    },
    'DNS': {
        "version": '1.0.0',
        "description": 'DNS解析、缓存、自定义DNS服务器',
        "category": 'net',
        "keywords": ['DNS', '域名', '解析', '缓存', '查询'],
        "dependencies": ['Socket'],
        "functions": [],
        "function_count": 0,
        "ffi_count": 2,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/DNS',
    },
    'GUI框架': {
        "version": '1.0.0',
        "description": 'GUI框架：窗口管理、事件循环、控件系统、布局引擎、样式系统',
        "category": 'dev',
        "keywords": ['GUI', '窗口', '事件循环', '控件', '布局'],
        "dependencies": [],
        "functions": ['createWindow', 'createEvent', 'createWidget', 'createLayout', 'createStyle', 'createApp', 'windowShow', 'windowHide', 'windowClose', 'windowSetTitle', 'windowSetSize', 'windowSetPosition', 'windowSetFullscreen', 'windowCenter', 'windowAddWidget', 'windowRemoveWidget', 'windowGetWidgetList', 'windowProcessEvent', 'windowPollEvents', 'windowBindEvent', 'windowIsClosed', 'widgetSetPosition', 'widgetSetSize', 'widgetSetVisible', 'widgetSetEnabled', 'widgetSetFocus', 'widgetSetStyle', 'widgetAddChild', 'widgetRemoveChild', 'widgetGetChildren', 'widgetSetEventHandler', 'widgetGetData', 'widgetSetData', 'widgetBindEvent', 'layoutAddWidget', 'layoutRemoveWidget', 'layoutSetMargin', 'layoutSetSpacing', 'layoutSetAlignment', 'layoutLayout', 'styleSetProperty', 'styleGetProperty', 'styleSetFont', 'styleSetColor', 'styleSetBgColor', 'styleSetBorder', 'styleSetPadding', 'styleSetMargin', 'styleSetBorderRadius', 'styleSetOpacity', 'styleSetShadow', 'styleSetBold', 'styleSetItalic', 'styleSetUnderline', 'styleClone', 'appRun', 'appExit', 'appAddWindow', 'appRemoveWindow', 'appGetWindows', 'appSetStyleSheet', 'appSetTimer', 'appStopTimer', 'appGetVersion', 'appEventLoop', 'getMsTime', 'getStatus', 'getVersion'],
        "function_count": 68,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/GUI框架',
    },
    'HTTP客户端': {
        "version": '1.0.0',
        "description": 'HTTP/1.1+2.0客户端，连接池、重定向、Cookie管理',
        "category": 'net',
        "keywords": ['HTTP', '客户端', '请求', '连接池', 'Cookie'],
        "dependencies": ['Socket', 'URL解析'],
        "functions": [],
        "function_count": 0,
        "ffi_count": 10,
        "has_source": True,
        "priority": 'P1',
        "stdlib_equivalent": None,
        "note": '需新建，基于 requests',
        "path": 'packages/HTTP客户端',
    },
    'HTTP服务端': {
        "version": '1.0.0',
        "description": '轻量HTTP服务器，路由、中间件、静态文件',
        "category": 'net',
        "keywords": ['HTTP', '服务端', '路由', '中间件', '静态文件'],
        "dependencies": ['Socket', 'URL解析'],
        "functions": ['创建HTTPServer(host,port):', 'add_route(server,method,path,handler):', 'add_static(server,url_prefix,dir_path):', 'start_server(server):', 'stop_server(server):', 'response_write_text(response,status_code,text,content_type):', 'response_write_json(response,status_code,json_str):', 'response_write_html(response,status_code,html):', 'response_write_file(response,file_path):', 'response_redirect(response,location,status_code):', 'response_set_header(response,name,value):', 'response_set_cookie(response,cookie):', 'responseNotFound(response):', 'responseInternalError(response,err_msg):'],
        "function_count": 14,
        "ffi_count": 16,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/HTTP服务端',
    },
    'JSON': {
        "version": '1.0.0',
        "description": 'JSON解析、序列化、流式读写、JSON Schema验证、JSON Pointer',
        "category": 'dev',
        "keywords": ['JSON', '解析', '序列化', 'Schema', 'Pointer'],
        "dependencies": [],
        "functions": ['是空白_内部', '是数字_内部', '是十六进制数字_内部', '十六进制值_内部', '跳过空白_内部', '解析字符串_内部', '码点转字符值_内部', '从码点构建_内部', '解析数字_内部', '字符串转整数_内部', '字符串转浮点_内部', '解析关键字_内部', '解析值_内部', '解析对象_内部', '解析数组_内部', '解析JSON', '安全解析JSON', '解析JSON文件', '序列化字符串_内部', '生成缩进_内部', '序列化值_内部', '序列化数组_内部', '序列化对象_内部', '序列化JSON', '序列化JSON文件', '取值形态', '是JSON对象', '是JSON数组', '是JSON字符串', '是JSON数字', '是JSON布尔', '解析Pointer令牌_内部', '编码Pointer令牌_内部', 'JSON指针获取', '分割Pointer_内部', 'JSON指针设置', 'JSON指针删除', '创建验证结果_内部', '验证结果是否有效', '验证结果获取错误列表', '验证Schema_内部', '验证型别_内部', '核对单个型别_内部', '列表转字符串_内部', '简单正则核对_内部', '完全核对_内部', '核对字符值_内部', '核对字符组_内部', '验证JSONSchema', 'JSON美化', 'JSON压缩', 'JSON合并', '深合并', 'JSON深度相等', 'JSON类型', 'JSON深合并'],
        "function_count": 56,
        "ffi_count": 2,
        "has_source": True,
        "priority": 'P0',
        "stdlib_equivalent": 'JSON',
        "note": '已有 Python 实现，桥接到 stdlib',
        "path": 'packages/JSON',
    },
    'JWT': {
        "version": '1.0.0',
        "description": 'JSON Web Token生成、验证、签名',
        "category": 'security',
        "keywords": ['JWT', 'JWS', 'JWE', '令牌', '签名', '验证'],
        "dependencies": [],
        "functions": [],
        "function_count": 0,
        "ffi_count": 12,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/JWT',
    },
    'Markdown': {
        "version": '1.0.0',
        "description": 'Markdown解析为AST、HTML渲染、GFM扩展',
        "category": 'dev',
        "keywords": ['Markdown', '解析', 'AST', 'HTML', 'GFM'],
        "dependencies": [],
        "functions": ['分割行', '解析Markdown', '解析Markdown文件', '渲染为HTML', '渲染Markdown为HTML', '获取所有链接', '统计文档'],
        "function_count": 7,
        "ffi_count": 2,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/Markdown',
    },
    'NoSQL连接器': {
        "version": '1.0.0',
        "description": 'Redis/MongoDB连接器，连接池与自动重连',
        "category": 'database',
        "keywords": ['NoSQL', 'Redis', 'MongoDB', '连接池', '缓存'],
        "dependencies": [],
        "functions": ['检查Redis连接', '执行重连', '检查Mongo连接', '构建集合全名', '连接Redis', '关闭Redis', '设置自动重连', '执行命令', '设置', '获取', '删除', '键是否存在', '设置过期', '键列表', '递增', '哈希设置', '哈希获取', '哈希获取全部', '哈希字段列表', '哈希删除字段', 'lpush', 'rpop', 'llen', 'lrange', 'sadd', 'smembers', 'scard', 'sismember', 'zadd', 'zrange', 'zcard', '发布消息', '订阅频道', '取消订阅', '连接MongoDB', '关闭MongoDB', '列出数据库', '列出集合', '插入文档', '插入多个文档', '查找文档', '查找一个文档', '更新文档', '更新多个文档', '删除文档', '删除多个文档', '计数文档', '聚合查询'],
        "function_count": 48,
        "ffi_count": 32,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/NoSQL连接器',
    },
    'OAuth客户端': {
        "version": '1.0.0',
        "description": 'OAuth 2.0客户端认证流程',
        "category": 'security',
        "keywords": ['OAuth', 'OAuth2', '认证', '授权', '令牌'],
        "dependencies": [],
        "functions": [],
        "function_count": 0,
        "ffi_count": 10,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/OAuth客户端',
    },
    'Redis绑定': {
        "version": '1.0.0',
        "description": 'Redis底层协议绑定：管道/事务/Lua脚本/Stream/Geo/位图/HyperLogLog/哨兵/集群',
        "category": 'dev',
        "keywords": ['Redis', '管道', '事务', 'Lua', 'Stream', '集群', '哨兵', 'Geo', '位图', 'HyperLogLog'],
        "dependencies": [],
        "functions": ['checkRedisConn', 'doReconnect', 'buildRESPCommand', 'escapeRESPArg', 'parseRESPReply', 'execRawCmd', 'execArgCmd', 'encodeRESP', 'decodeRESP', 'connectRedis', 'closeRedis', 'setAutoReconnect', 'setTimeout', 'enableKeepAlive', 'execCommand', 'execCommandWithArgs', 'getError', 'createPipeline', 'pipelineAddCmd', 'pipelineAddCmdArgs', 'pipelineExec', 'pipelineGetResults', 'pipelineReset', 'createTransaction', 'txBegin', 'txWatch', 'txAddCmd', 'txExec', 'txDiscard', 'evalScript', 'evalShaScript', 'loadScript', 'scriptExists', 'flushScriptCache', 'killScript', 'pSubscribe', 'pUnsubscribe', 'publish', 'listActiveChannels', 'channelNumSub', 'numPatternSub', 'xadd', 'xread', 'xreadMulti', 'xrange', 'xgroupCreate', 'xreadgroup', 'xack', 'xlen', 'xdel', 'geoAdd', 'geoAddBatch', 'geoGet', 'geoDist', 'geoRadius', 'geoRadiusByMember', 'geoHash', 'setBit', 'getBit', 'bitCount', 'bitOp', 'bitPos', 'pfadd', 'pfcount', 'pfmerge', 'createSentinel', 'sentinelDiscoverMaster', 'sentinelGetMasterInfo', 'sentinelFailover', 'closeSentinel', 'createCluster', 'clusterBuildConnMap', 'clusterCalcSlot', 'clusterGetNode', 'clusterExec', 'clusterNodes', 'clusterInfo', 'clusterSlots', 'closeCluster', 'setKey', 'getKey', 'delKey', 'existsKey', 'expireKey', 'ttlKey', 'randomKey', 'keyType', 'renameKey', 'incr', 'ping'],
        "function_count": 90,
        "ffi_count": 13,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/Redis绑定',
    },
    'RPC框架': {
        "version": '1.0.0',
        "description": '基于TCP的RPC框架：服务注册、负载均衡、JSON序列化、超时重试、心跳检测',
        "category": 'dev',
        "keywords": ['RPC', '远程调用', '服务注册', '负载均衡', '序列化'],
        "dependencies": [],
        "functions": ['创建服务注册中心(ID):', '注册中心注册(注册中心,服务描述):', '注册中心注销(注册中心,service_name,版本):', '注册中心发现(注册中心,service_name):', '注册中心获取所有服务(注册中心):', '注册中心健康检查(注册中心,service_name,版本,是否健康):', '创建RPC客户端(注册中心,timeout_secs,负载均衡策略,重试次数):', '客户端调用(客户端,service_name,method_name,params):', '客户端调用批量(客户端,调用列表):', '客户端心跳(客户端,service_name,版本):', '创建RPC服务端(service_name,端口):', '服务端注册方法(服务端,method_name,处理函数):', '服务端启动(服务端):', '服务端停止(服务端):', '服务端处理请求(服务端,请求):', '服务端心跳检测(服务端,间隔秒数):', '创建轮询负载均衡:', '创建随机负载均衡:', '创建加权负载均衡(权重字典):', '负载均衡选择(策略,服务列表):', '范围(开始,结束):', '序列化请求(请求):', '反序列化请求(JSON字符串):', '序列化响应(响应):', '反序列化响应(JSON字符串):'],
        "function_count": 25,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/RPC框架',
    },
    'Socket': {
        "version": '1.0.0',
        "description": 'TCP/UDP/Unix域套接字，阻塞与非阻塞模式',
        "category": 'net',
        "keywords": ['Socket', 'TCP', 'UDP', '网络', '套接字'],
        "dependencies": [],
        "functions": ['创建TCPSocket:', '绑定(sock,地址,端口):', '监听(sock,backlog):', '接受(sock):', '连接TCP(host,port):', '发送(连接,数据):', '接收(连接,最大长度):', '设置非阻塞(sock,nonblocking):', '创建UDPSocket:', '绑定UDP(sock,地址,端口):', '发送UDP(sock,数据,host,port):', '接收UDP(sock,最大长度):', '获取本地地址(sock):', '获取远程地址(sock):', 'select读写(可读列表,可写列表,超时秒):', '获取错误信息(sock):', '将主机名转为IP(主机名):', '解析IP地址(ip):', '主机转网络字节序(host):', '网络转主机字节序(net):', 'sock有效(sock):', '连接有效(连接):'],
        "function_count": 22,
        "ffi_count": 19,
        "has_source": True,
        "priority": 'P1',
        "stdlib_equivalent": None,
        "note": '需新建，基于 socket',
        "path": 'packages/Socket',
    },
    'SQLite': {
        "version": '1.0.0',
        "description": 'SQLite封装，ORM映射、迁移、查询构建器',
        "category": 'database',
        "keywords": ['SQLite', 'ORM', '数据库', '迁移', '查询'],
        "dependencies": [],
        "functions": [],
        "function_count": 0,
        "ffi_count": 23,
        "has_source": True,
        "priority": 'P1',
        "stdlib_equivalent": None,
        "note": '需新建，基于 sqlite3',
        "path": 'packages/SQLite',
    },
    'TOML': {
        "version": '1.0.0',
        "description": 'TOML配置解析与生成，支持完整1.0规范',
        "category": 'dev',
        "keywords": ['TOML', '配置', '解析', '序列化'],
        "dependencies": [],
        "functions": ['isdigit', 'ishex', 'isspace', 'isalpha', 'isbarekey', 'trim', 'rtrim', 'ltrim', 'splitlines', '范围', 'curr', 'advance', 'skipws', 'skipwscomment', 'expectchar', 'parseesc', 'parsehex', 'parsebasicstr', 'parsemlbasicstr', 'parseliteralstr', 'parsemlliteralstr', 'parsestr', 'parsenum', 'readdecdigits', 'readhexdigits', 'readoctdigits', 'readbindigits', 'parsedecint', 'parsehexint', 'parseoctint', 'parsebinint', 'parsefloat', 'parsebool', 'parsedatetime', 'readtwodigits', 'parsearray', 'parseinlinetable', 'parsevalue', 'parsebarekey', 'parsequotedkey', 'parsesinglekey', 'parsekey', 'parsekv', 'parsetableheader', 'parsetablearrayheader', 'navigateto', 'setnested', 'parsedoc', '解析TOML', '解析TOML文件', 'issimpleval', 'isbasetype', 'isinlinetablecandidate', 'needsquotedkey', 'serializekey', 'escapestr', 'serializeval', 'padnum', 'serializetablecontent', '序列化TOML', 'TOML获取', 'TOML设置', 'TOML深度融合', 'TOML转JSON', 'escapejsonstr', 'TOML验证', 'checkbracketmatch', 'checkhasequals'],
        "function_count": 68,
        "ffi_count": 4,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/TOML',
    },
    'URL解析': {
        "version": '1.0.0',
        "description": 'URL解析、构建、编码、查询参数处理',
        "category": 'net',
        "keywords": ['URL', '解析', '构建', '查询参数', '编码'],
        "dependencies": ['二进制编码'],
        "functions": [],
        "function_count": 0,
        "ffi_count": 2,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/URL解析',
    },
    'WebSocket': {
        "version": '1.0.0',
        "description": 'WebSocket客户端与服务端，消息帧、心跳、自动重连',
        "category": 'net',
        "keywords": ['WebSocket', 'WS', '消息', '实时', '心跳'],
        "dependencies": ['Socket', 'HTTP客户端'],
        "functions": ['find(文本,子串):', 'starts_with(文本,前缀):', 'contains(文本,子串):', '连接WS(url,cb):', '连接WSS(url,cb):', '发送文本(连接,文本):', '发送二进制(连接,数据):', '发送Ping(连接):', '发送Pong(连接,载荷数据):', '关闭连接(连接,关闭码,原因):', '接收消息(连接,cb):', '开始心跳(连接,间隔秒):', '设置自动重连(连接,启用):', '获取连接状态(连接):', '是否活跃(连接):', '接受连接(服务器tcp_conn,请求文本,cb):'],
        "function_count": 16,
        "ffi_count": 11,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/WebSocket',
    },
    'Web框架': {
        "version": '1.0.0',
        "description": 'Web框架：依赖注入/控制器/模型绑定/验证器/视图引擎/会话/CORS/速率限制/日志',
        "category": 'dev',
        "keywords": ['Web', '框架', 'MVC', '依赖注入', '控制器', '验证', '会话'],
        "dependencies": ['HTTP服务端'],
        "functions": [],
        "function_count": 0,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/Web框架',
    },
    'XML': {
        "version": '1.0.0',
        "description": 'XML解析（DOM/SAX）、XPath、XSLT转换，底层绑定libxml2',
        "category": 'dev',
        "keywords": ['XML', '解析', 'DOM', 'SAX', 'XPath'],
        "dependencies": [],
        "functions": ['解析XML', '解析XML文件', '释放XML文档', '获取根元素', '元素名称', '元素属性', '元素属性存在', '元素文本', '元素子元素', '元素父元素', '元素下一个兄弟', '元素前一个兄弟', 'XPath查询节点', 'XPath查询字符串', 'XPath查询第一个节点', '序列化XML', '序列化XML文档', '开始SAX解析', 'SAX解析更多', '结束SAX解析', 'XSLT转换', '元素属性名称列表', '元素所有属性', '遍历元素树', '查找元素', '收集_内部', '查找第一个元素'],
        "function_count": 27,
        "ffi_count": 23,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/XML',
    },
    'YAML': {
        "version": '1.0.0',
        "description": 'YAML解析与生成，支持多文档、锚点引用',
        "category": 'dev',
        "keywords": ['YAML', '解析', '序列化', '配置', '锚点'],
        "dependencies": [],
        "functions": ['是空白_内部', '是换行_内部', '是空白或换行_内部', '是数字_内部', '是十六进制数字_内部', '是字母_内部', '是字母或数字_内部', '是标识符字符值_内部', '是可打印_内部', '十六进制值_内部', '跳过空白_内部', '跳过空白和注释_内部', '获取缩进_内部', '跳过缩进_内部', '跳到行尾_内部', '跳过换行_内部', '获取行内容_内部', '是文档分隔符_内部', '获取下一行_内部', '解析双引号字符串_内部', '解析单引号字符串_内部', '解析字面量块_内部', '解析折叠块_内部', '解析空值_内部', '解析布尔值_内部', '解析整数_内部', '解析十六进制_内部', '解析八进制_内部', '解析十进制_内部', '解析浮点数_内部', '解析浮点字符串_内部', '是NaN_内部', '解析时间戳_内部', '解析纯量_内部', '去除首尾空格_内部', '解析纯量值_内部', '是键_内部', '解析键_内部', '解析值_内部', '解析流式数组_内部', '解析块数组_内部', '解析流式对象_内部', '解析块对象_内部', '解析锚点_内部', '解析别名_内部', '解析标签_内部', '解析YAML', '解析YAML文件', '解析YAML多文档', '解析YAML多文档文件', '生成缩进_内部', '需要引号_内部', '序列化YAML字符串_内部', '序列化YAML值_内部', '序列化YAML列表_内部', '序列化YAML对象_内部', '是简单值_内部', '序列化YAML', '序列化YAML文件', '是YAML对象', '是YAML数组', 'YAML合并', 'YAML验证'],
        "function_count": 63,
        "ffi_count": 2,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/YAML',
    },
    '中间件集合': {
        "version": '1.0.0',
        "description": '可复用中间件：CORS、限流、压缩、日志、恢复、会话、静态文件、缓存控制',
        "category": 'dev',
        "keywords": ['中间件', 'CORS', '限流', '日志', '恢复', '会话'],
        "dependencies": [],
        "functions": ['内部范围', '内部整数转字符串', '内部随机字符串', '内部包含', '内部以开始', '内部转为小写', '内部转为大写', '内部分割', '内部去除空白', '创建中间件请求', '创建中间件响应：', '响应设置头', '响应写文本', '响应写JSON', '响应写HTML', '创建CORS中间件', '创建令牌桶', '令牌桶消耗', '令牌桶重置', '创建限流中间件', '创建日志中间件', '创建恢复中间件', '创建会话存储', '会话存储获取', '会话存储设置', '会话存储删除', '会话存储清理', '创建会话中间件', '创建压缩中间件', '创建静态文件中间件', '创建缓存控制中间件', '创建中间件链', '中间件链执行', '中间件链重置'],
        "function_count": 34,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/中间件集合',
    },
    '事件驱动': {
        "version": '1.0.0',
        "description": '事件驱动编程模型',
        "category": 'language',
        "keywords": ['事件', 'EventEmitter', 'EventBus', '事件总线', '监听器'],
        "dependencies": [],
        "functions": ['创建事件循环', '事件循环添加事件', '事件循环运行', '事件循环停止', '创建事件', '触发事件'],
        "function_count": 6,
        "ffi_count": 7,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/事件驱动',
    },
    '二进制编码': {
        "version": '1.0.0',
        "description": 'Base64/Base32/Hex/URL编码/百分号编码',
        "category": 'dev',
        "keywords": ['编码', 'Base64', 'Base32', 'Hex', 'URL', '百分号'],
        "dependencies": [],
        "functions": ['字符串转字节', '字节转字符串', '是十六进制字符', '十六进制值', '是空白字符', '是URL安全字符', '字节转十六进制', '字节转十六进制大写', 'Base64编码', 'Base64编码字符串', 'Base64解码', 'Base64解码为字符串', 'Base64URL编码', 'Base64URL解码', 'Base32编码', 'Base32编码字符串', 'Base32解码', 'Base32解码为字符串', 'Hex编码', 'Hex编码大写', 'Hex解码', 'URL编码', 'URL解码', 'URL编码查询', 'URL解码查询', '百分号编码', '百分号解码'],
        "function_count": 27,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/二进制编码',
    },
    '云存储': {
        "version": '1.0.0',
        "description": '对象存储：上传下载、签名URL、桶管理、访问控制、缩略图处理',
        "category": 'dev',
        "keywords": ['云存储', '对象存储', 'OSS', 'COS', '上传下载', '签名URL'],
        "dependencies": [],
        "functions": ['创建阿里云OSS配置', '创建腾讯云COS配置', '创建AWS', '创建桶', '删除桶', '获取桶信息', '列出桶', '列出对象', '上传文件', '上传流式', '上传字符串', '下载文件', '下载文件到文件', '获取对象信息', '删除对象', '批量删除对象', '复制对象', '移动对象', '生成签名URL', '生成预签名URL', '设置对象ACL', '设置桶ACL', '获取对象ACL', '生成上传策略', '签名POST政策', '设置对象元数据', '获取对象元数据', '生成缩略图URL', '生成CDNURL', '判断对象存在', '获取对象大小', '设置生命周期', '上传进度回调'],
        "function_count": 33,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/云存储',
    },
    '代码格式化': {
        "version": '1.0.0',
        "description": '光明代码格式化器，可配置风格',
        "category": 'dev',
        "keywords": ['格式化', '代码', '风格', '美化'],
        "dependencies": [],
        "functions": ['创建默认选项', '创建紧凑选项', '加载选项配置', '计算缩进字符串', '检测缩进风格', '移除多余空行', '统一空行', '修复末尾空行', '规范化空格', '格式化代码', '格式化文件', '格式化目录', '检查格式', '检查格式问题'],
        "function_count": 14,
        "ffi_count": 6,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/代码格式化',
    },
    '任务队列': {
        "version": '1.0.0',
        "description": '任务队列系统：异步任务、延迟任务、定时任务、重试策略、优先级、并发控制',
        "category": 'dev',
        "keywords": ['任务队列', '异步', '延迟', '定时', '重试'],
        "dependencies": [],
        "functions": ['取时间戳', '创建任务队列', '创建任务', '任务队列添加任务', '任务队列添加任务简便', '任务队列添加延迟任务', '任务队列添加定时任务', '队列触发事件', '任务队列处理下一个', '任务队列处理所有', '任务队列处理所有异步', '任务队列暂停', '任务队列恢复', '任务队列停止', '任务队列获取统计', '任务队列获取任务', '任务队列重试失败任务', '任务队列清理已完成', '任务队列注册事件监听器', '任务队列处理定时任务', '检查定时'],
        "function_count": 21,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/任务队列',
    },
    '全文搜索': {
        "version": '1.0.0',
        "description": '倒排索引、中文分词、TF-IDF/BM25排序、布尔查询、短语搜索、模糊搜索、字段索引',
        "category": 'dev',
        "keywords": ['搜索', '全文', '索引', '分词', 'TF-IDF', 'BM25'],
        "dependencies": [],
        "functions": ['字母数字检测', '计算编辑距离', '是停用词', '添加停用词', '加载停用词', '中文分词', '英文分词', '通用分词', '创建索引', '计算TF', '计算IDF', '计算TFIDF', '计算BM25'],
        "function_count": 13,
        "ffi_count": 3,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/全文搜索',
    },
    '内存管理': {
        "version": '1.0.0',
        "description": '智能指针、内存池、引用计数、RAII工具',
        "category": 'dev',
        "keywords": ['内存', '智能指针', 'RAII', '内存池'],
        "dependencies": [],
        "functions": ['创建智能指针', '智能指针取值', '智能指针设置', '智能指针获取引用计数', '智能指针增加引用', '智能指针减少引用', '智能指针是否为最后一个引用', '内存分配', '内存释放', '内存复制', '内存清零', '内存比较'],
        "function_count": 12,
        "ffi_count": 5,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/内存管理',
    },
    '加密算法': {
        "version": '1.0.0',
        "description": '加密算法集合',
        "category": 'security',
        "keywords": ['加密', '密码', 'AES', 'RSA', '算法'],
        "dependencies": [],
        "functions": ['加密', '解密', '生成密钥', '生成IV', '获取算法名称'],
        "function_count": 5,
        "ffi_count": 5,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/加密算法',
    },
    '包管理增强': {
        "version": '1.0.0',
        "description": '依赖锁定、版本冲突检测、工作区管理',
        "category": 'dev',
        "keywords": ['包管理', '依赖', '版本', '锁定', '工作区'],
        "dependencies": [],
        "functions": [],
        "function_count": 0,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/包管理增强',
    },
    '协程': {
        "version": '1.0.0',
        "description": '协程库：协程调度、挂起恢复、通道通信、生成器、选择器',
        "category": 'dev',
        "keywords": ['协程', '调度', '通道', '生成器', '异步'],
        "dependencies": [],
        "functions": ['createScheduler', 'createChannel', 'createBufferedChannel', 'createSelector', 'createGenerator', 'schedulerCreateCoro', 'schedulerStartCoro', 'schedulerSuspendCoro', 'schedulerResumeCoro', 'schedulerCancelCoro', 'schedulerRunStep', 'schedulerRunAll', 'schedulerRun', 'schedulerStop', 'schedulerGetCoro', 'schedulerGetAllCoros', 'schedulerGetStats', 'schedulerWaitCoro', 'schedulerWaitAll', 'schedulerWaitAny', 'schedulerYield', 'channelSend', 'channelRecv', 'channelTrySend', 'channelTryRecv', 'channelClose', 'channelIsClosed', 'channelLen', 'channelCap', 'channelClear', 'selectorAddSend', 'selectorAddRecv', 'selectorSetDefault', 'selectorSelect', 'generatorNext', 'generatorCollect', 'generatorReset'],
        "function_count": 37,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/协程',
    },
    '压缩算法': {
        "version": '1.0.0',
        "description": 'gzip、zlib、lz4、zstd压缩与解压的光明封装',
        "category": 'dev',
        "keywords": ['压缩', 'gzip', 'zlib', 'lz4', 'zstd'],
        "dependencies": [],
        "functions": ['gzip压缩', 'gzip解压', 'zlib压缩', 'zlib解压', 'lz4压缩', 'lz4解压', 'zstd压缩', 'zstd解压'],
        "function_count": 8,
        "ffi_count": 9,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/压缩算法',
    },
    '命令行参数': {
        "version": '1.0.0',
        "description": '参数解析、子命令、帮助文本生成、自动补全',
        "category": 'dev',
        "keywords": ['命令行', '参数', 'CLI', '子命令', '帮助'],
        "dependencies": [],
        "functions": ['新建参数定义', '设置短名称', '设置默认值', '设置必需', '新建子命令', '子命令添加参数', '解析参数', '获取参数值', '生成帮助文本'],
        "function_count": 9,
        "ffi_count": 4,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/命令行参数',
    },
    '哈希': {
        "version": '1.0.0',
        "description": 'MD5/SHA1/SHA256/SHA512/SHA3-256/BLAKE3哈希，HMAC，流式哈希，文件哈希',
        "category": 'dev',
        "keywords": ['哈希', 'MD5', 'SHA', 'HMAC', '加密'],
        "dependencies": [],
        "functions": ['字节转十六进制', '字节转Base64', '创建哈希', '哈希上下文更新', '哈希上下文完成', '哈希上下文完成字节', '哈希上下文重置', '哈希上下文释放', '哈希上下文获取摘要大小', '哈希', 'MD5哈希', 'SHA1哈希', 'SHA256哈希', 'SHA512哈希', 'SHA3_256哈希', 'BLAKE3哈希', '哈希字节', '创建HMAC', 'hmac_ctx更新', 'hmac_ctx完成', 'hmac_ctx完成字节', 'hmac_ctx重置', 'hmac_ctx释放', 'HMAC哈希', 'HMAC哈希字节', '文件哈希', '文件哈希字节', '十六进制转字节', '哈希相等', '获取算法名称', '获取算法摘要大小', '获取所有算法'],
        "function_count": 32,
        "ffi_count": 24,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/哈希',
    },
    '哈希算法': {
        "version": '1.0.0',
        "description": '哈希算法集合',
        "category": 'security',
        "keywords": ['哈希', 'hash', 'SHA', 'MD5', '摘要'],
        "dependencies": [],
        "functions": ['字节转十六进制', '字节转Base64', '创建哈希', '哈希上下文更新', '哈希上下文完成', '哈希上下文完成字节', '哈希上下文重置', '哈希上下文释放', '哈希上下文获取摘要大小', '哈希', 'MD5哈希', 'SHA1哈希', 'SHA256哈希', 'SHA512哈希', 'SHA3_256哈希', 'BLAKE3哈希', '哈希字节', '创建HMAC', 'hmac_ctx更新', 'hmac_ctx完成', 'hmac_ctx完成字节', 'hmac_ctx重置', 'hmac_ctx释放', 'HMAC哈希', 'HMAC哈希字节', '文件哈希', '文件哈希字节', '十六进制转字节', '哈希相等', '获取算法名称', '获取算法摘要大小', '获取所有算法'],
        "function_count": 32,
        "ffi_count": 24,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/哈希算法',
    },
    '响应式编程': {
        "version": '1.0.0',
        "description": 'Observable模式、事件流、操作符',
        "category": 'language',
        "keywords": ['响应式', '流', '观察者', '订阅', '事件'],
        "dependencies": [],
        "functions": [],
        "function_count": 0,
        "ffi_count": 18,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/响应式编程',
    },
    '图像处理': {
        "version": '1.0.0',
        "description": '图像滤镜、变换、格式转换',
        "category": 'media',
        "keywords": ['图像', '滤镜', '转换', '色彩', '像素'],
        "dependencies": [],
        "functions": [],
        "function_count": 0,
        "ffi_count": 18,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/图像处理',
    },
    '图像处理增强': {
        "version": '1.0.0',
        "description": '图像处理增强库：滤镜、卷积、形态学、直方图、边缘检测、特征提取',
        "category": 'dev',
        "keywords": ['图像处理', '滤镜', '卷积', '形态学', '直方图', '边缘检测'],
        "dependencies": [],
        "functions": ['createImage', 'createImageFromPixels', 'imageGetPixel', 'imageSetPixel', 'imageGetRegion', 'imageCopy', 'imageResize', 'imageToGray', 'imageToRGB', 'imageToRGBA', 'imageFlip', 'imageRotate', 'imageAdjustBrightness', 'imageAdjustContrast', 'imageAdjustSaturation', 'imageAdjustHue', 'imageAdjustGamma', 'imageInvert', 'imageThreshold', 'imageHistogramEqualize', 'imageGaussianBlur', 'imageBoxBlur', 'imageMedianFilter', 'imageSharpen', 'imageEmboss', 'imageConvolve', 'imageDilate', 'imageErode', 'imageOpen', 'imageClose', 'imageCannyEdge', 'imageSobelEdge', 'imageCalcHistogram', 'imageOTSUThreshold', 'imageCornerDetect', 'imageAdd', 'imageBlend', 'imageMultiply', 'imageNormalize'],
        "function_count": 39,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/图像处理增强',
    },
    '图像编解码': {
        "version": '1.0.0',
        "description": '图像编解码库：PNG/JPEG/BMP/GIF/WebP解析、生成、格式转换',
        "category": 'dev',
        "keywords": ['图像编解码', 'PNG', 'JPEG', 'BMP', 'GIF', 'WebP'],
        "dependencies": [],
        "functions": ['readPNG', 'writePNG', 'readJPEG', 'writeJPEG', 'readBMP', 'writeBMP', 'readGIF', 'writeGIF', 'readWebP', 'writeWebP', 'formatConvert', 'readImage', 'writeImage', 'getImageInfo'],
        "function_count": 14,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/图像编解码',
    },
    '图形渲染': {
        "version": '1.0.0',
        "description": '2D/3D图形渲染管线',
        "category": 'graphics',
        "keywords": ['图形', '渲染', '着色器', '纹理', '网格'],
        "dependencies": [],
        "functions": [],
        "function_count": 0,
        "ffi_count": 14,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/图形渲染',
    },
    '图表': {
        "version": '1.0.0',
        "description": '图表库：折线图、柱状图、饼图、散点图、雷达图、面积图、SVG导出',
        "category": 'dev',
        "keywords": ['图表', '折线图', '柱状图', '饼图', '散点图', '雷达图'],
        "dependencies": [],
        "functions": ['createChartConfig', 'createDataSeries', 'createDataPoint', 'createAxis', 'drawLineChart', 'drawBarChart', 'drawPieChart', 'drawScatterChart', 'drawRadarChart', 'drawAreaChart', 'exportSVG'],
        "function_count": 11,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/图表',
    },
    '地理计算': {
        "version": '1.0.0',
        "description": '地理计算库：坐标转换、距离计算、GeoJSON解析、空间索引、地理围栏',
        "category": 'dev',
        "keywords": ['地理', '坐标', '距离', 'GeoJSON', '空间索引', '地理围栏'],
        "dependencies": [],
        "functions": ['创建坐标', '计算距离', '创建边界框', '创建地理围栏', '创建围栏管理器'],
        "function_count": 5,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/地理计算',
    },
    '字体渲染': {
        "version": '1.0.0',
        "description": '字体渲染库：字体解析、字形缓存、文字绘制、换行计算、抗锯齿',
        "category": 'dev',
        "keywords": ['字体', '文字渲染', '字形缓存', '换行', '抗锯齿'],
        "dependencies": [],
        "functions": ['createFont', 'createFontMetrics', 'createGlyph', 'measureTextWidth', 'measureTextHeight', 'measureText', 'loadFont', 'getGlyph', 'drawText', 'drawTextToCanvas', 'renderText', 'renderTextLine', 'wrapText', 'calcLineBreaks', 'setFontSize', 'setFontStyle', 'getFontMetrics', 'getFontName', 'getFontFamily', 'getAllGlyphs', 'clearGlyphCache'],
        "function_count": 21,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/字体渲染',
    },
    '字符串处理': {
        "version": '1.0.0',
        "description": 'Unicode规范化、编码转换、模板插值、模糊匹配',
        "category": 'dev',
        "keywords": ['字符串', 'Unicode', '编码', '模板'],
        "dependencies": [],
        "functions": ['normalizeNFC', 'normalizeNFD', 'isCombiningChar', 'toUTF8', 'fromUTF8', 'templateInterpolate', 'editDistance', 'fuzzyMatch', 'fuzzyMatchSimilarity', 'strReverse', 'strRepeat', 'strTruncate', 'toCamelCase', 'toSnakeCase', 'toKebabCase', 'capitalizeFirst', 'capitalizeWords', 'trimWhitespace', 'trimPrefix', 'trimSuffix', 'countChars', 'countLines', 'getSubstring'],
        "function_count": 23,
        "ffi_count": 6,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/字符串处理',
    },
    '密码哈希': {
        "version": '1.0.0',
        "description": 'bcrypt/scrypt/argon2id密码哈希，密码强度校验，常见密码黑名单，防时序攻击',
        "category": 'dev',
        "keywords": ['密码', '哈希', 'bcrypt', 'scrypt', 'argon2', '安全'],
        "dependencies": [],
        "functions": ['哈希密码', '验证密码', '生成盐值', '获取算法名称'],
        "function_count": 4,
        "ffi_count": 7,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/密码哈希',
    },
    '对称加密': {
        "version": '1.0.0',
        "description": 'AES/ChaCha20对称加密，支持ECB/CBC/CTR/GCM模式，PKCS7填充，认证加密',
        "category": 'dev',
        "keywords": ['加密', 'AES', 'ChaCha20', 'GCM', '对称'],
        "dependencies": [],
        "functions": ['get_keylen', 'get_ivlen', 'algo_name', 'mode_name', 'check_keylen', 'check_ivlen', 'is_gcm_mode', 'is_aead_mode', 'is_stream', '生成密钥', '生成IV', '生成Nonce', 'create_enc', 'PKCS7填充', 'PKCS7去填充', 'byte_at', 'substr', 'encrypt', 'decrypt', 'chacha20_enc', 'chacha20_dec', 'get_tag', 'set_tag', 'free_enc', 'ChaCha20Poly1305加密', 'ChaCha20Poly1305解密', '字符串加密', '字符串解密', '打包加密数据', '解包加密数据', '获取算法信息', '获取模式信息'],
        "function_count": 32,
        "ffi_count": 20,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/对称加密',
    },
    '对话框': {
        "version": '1.0.0',
        "description": '对话框组件：消息框、文件选择、颜色选择、输入框、确认框、进度对话框',
        "category": 'dev',
        "keywords": ['对话框', '消息框', '文件选择', '颜色选择', '输入框'],
        "dependencies": [],
        "functions": [],
        "function_count": 0,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/对话框',
    },
    '对象存储': {
        "version": '1.0.0',
        "description": 'S3兼容协议客户端：桶操作/对象管理/分段上传/预签名URL/元数据/ACL/版本管理',
        "category": 'dev',
        "keywords": ['S3', '对象存储', 'OSS', 'MinIO', '云存储', '文件'],
        "dependencies": ['HTTP客户端'],
        "functions": ['创建客户端', '列举桶', '创建桶', '删除桶', '桶是否存在', '上传对象', '下载对象', '删除对象', '列举对象', '复制对象', '对象元数据', '开始分段上传', '上传分段', '完成分段上传', '中止分段上传', '生成预签名URL', '设置对象ACL', '获取对象ACL', '启用版本管理', '暂停版本管理', '列举版本', '设置生命周期规则', '获取生命周期规则', '删除生命周期规则', '设置CORS规则', '获取CORS规则', '删除CORS规则', '流式上传', '流式下载', '范围下载', '断点续传上传', '断言'],
        "function_count": 32,
        "ffi_count": 8,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/对象存储',
    },
    '并行计算': {
        "version": '1.0.0',
        "description": '并行计算库：线程池、任务并行、数据并行、并行归约、并行排序',
        "category": 'dev',
        "keywords": ['并行', '线程池', '任务并行', '数据并行', '归约'],
        "dependencies": [],
        "functions": [],
        "function_count": 0,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/并行计算',
    },
    '异步运行时': {
        "version": '1.0.0',
        "description": '异步运行时：事件循环、Future/Promise、定时器、任务调度、异步IO',
        "category": 'dev',
        "keywords": ['异步', '事件循环', 'Future', 'Promise', '定时器', 'IO'],
        "dependencies": [],
        "functions": ['创建Future', '创建Future完成', '创建Future失败', '未来完成', '未来拒绝', '未来等待', '未来等待超时', '未来添加回调', '未来添加错误回调', '未来是否完成', '未来是否失败', '未来链式调用', '未来链式回调', '未来异常处理', '未来取消', '未来获取结果', '创建Promise', 'Promise执行', 'Promise解决', 'Promise拒绝', 'Promise然后', 'Promise捕获', 'Promise最终', 'Promise全部', 'Promise竞速', 'Promise全部完成', 'Promise任意', 'Promise解决已完成', 'Promise拒绝已完成', '创建事件循环', '事件循环运行', '事件循环运行单次', '事件循环停止', '事件循环暂停', '事件循环恢复', '事件循环是否运行中', '事件循环设置超时', '事件循环设置间隔', '事件循环清除定时器', '事件循环清除间隔', '事件循环立即执行', '事件循环创建任务', '事件循环任务执行器', '异步任务等待', '异步任务取消', '事件循环等待所有', '事件循环等待任意', '事件循环注册输入输出', '事件循环注销输入输出', '事件循环输入输出轮询', '事件循环睡眠', '事件循环睡眠回调', '事件循环延迟', '事件循环获取统计'],
        "function_count": 54,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/异步运行时',
    },
    '性能分析': {
        "version": '1.0.0',
        "description": 'CPU采样、内存分析、火焰图生成',
        "category": 'dev',
        "keywords": ['性能', '分析', 'CPU', '内存', '火焰图', '采样'],
        "dependencies": [],
        "functions": ['开始CPU采样', '停止CPU采样', '获取CPU采样', '按值降序排序', '排序节点递归', '生成火焰图节点', '生成火焰图', '生成火焰图SVG', '最大深度计算', '绘制节点SVG', '生成节点颜色', '转义SVG', '生成火焰图HTML', '字符串替换', '字符串长度', '创建内存快照', '获取内存使用量', '获取内存峰值', '比较内存快照', '内存泄漏检测', '开始计时', '结束计时', '计时器耗时', '测量执行时间', '测量多次', '创建性能报告', '添加CPU采样', '添加内存快照', '添加计时器', '生成报告', '生成文本报告', '生成HTML报告', '格式化字节', '检测热点函数', '检测热点代码行', '生成调用树', '高精度计时器', '当前线程ID', '当前进程ID'],
        "function_count": 39,
        "ffi_count": 9,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/性能分析',
    },
    '排序与搜索': {
        "version": '1.0.0',
        "description": '快速排序、归并排序、插入排序、二分搜索、模糊搜索、TopK',
        "category": 'dev',
        "keywords": ['排序', '搜索', '二分', 'TopK'],
        "dependencies": [],
        "functions": ['选取中值', '快排', '归并排', '归并合并', '插入排', '二分查', '模糊查', '查找子串', '按位置排', 'TopK', '创建最小堆', '堆上浮', '堆下沉', '堆插入', '堆弹出', '堆窥视', '堆是否为空', '反转列表'],
        "function_count": 18,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/排序与搜索',
    },
    '控件库': {
        "version": '1.0.0',
        "description": '控件库：按钮、输入框、表格、树形控件、选项卡、标签、复选框、进度条、滑块',
        "category": 'dev',
        "keywords": ['控件', '按钮', '输入框', '表格', '树形', '选项卡'],
        "dependencies": [],
        "functions": ['createButton', 'buttonSetText', 'buttonSetEnabled', 'buttonClick', 'buttonSetIcon', 'createInputBox', 'inputBoxSetText', 'inputBoxGetText', 'inputBoxSetReadonly', 'inputBoxSetPasswordMode', 'inputBoxSelectAll', 'inputBoxClear', 'createLabel', 'labelSetText', 'labelSetAlignment', 'createCheckBox', 'checkBoxIsChecked', 'checkBoxSetChecked', 'checkBoxToggle', 'createRadioButton', 'radioButtonIsChecked', 'radioButtonSetChecked', 'createComboBox', 'comboBoxGetSelectedText', 'comboBoxGetSelectedIndex', 'comboBoxSetSelected', 'comboBoxAddOption', 'comboBoxRemoveOption', 'createListBox', 'listBoxGetSelectedItems', 'listBoxAddOption', 'listBoxRemoveOption', 'listBoxClear', 'createTable', 'tableAddRow', 'tableRemoveRow', 'tableGetSelectedRows', 'tableSort', 'tableClearAll', 'tableUpdateRow', 'tableGetRowCount', 'createTreeView', 'treeViewAddNode', 'treeViewRemoveNode', 'treeViewExpandNode', 'treeViewCollapseNode', 'treeViewGetSelectedNode', 'treeViewExpandAll', 'treeViewCollapseAll', 'createTabControl', 'tabControlAddPage', 'tabControlRemovePage', 'tabControlSelectPage', 'tabControlGetCurrentPage', 'tabControlGetPageCount', 'createProgressBar', 'progressBarSetValue', 'progressBarGetValue', 'progressBarSetIndeterminate', 'progressBarIncrement', 'createSlider', 'sliderSetValue', 'sliderGetValue', 'sliderSetRange', 'createMenu', 'menuShow', 'menuHide', 'menuAddItem', 'menuAddSeparator'],
        "function_count": 69,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/控件库',
    },
    '支付集成': {
        "version": '1.0.0',
        "description": '支付网关集成：微信支付、支付宝、银联、签名验证、通知处理、订单查询',
        "category": 'dev',
        "keywords": ['支付', '微信支付', '支付宝', '银联', '签名'],
        "dependencies": [],
        "functions": ['创建微信支付配置', '创建支付宝配置', '创建支付订单', '创建支付请求', '微信支付统一下单', '微信支付查询订单', '微信支付close订单', '微信支付退款', '支付宝创建订单', '支付宝查询订单', '支付宝退款', '验证支付通知', '解析支付通知', '生成支付签名', '微信支付HMACSHA256签名', '支付宝RSA2签名', '创建二维码内容', '创建二维码URL', '检测支付状态', '获取支付结果', '创建退款请求', '处理异步通知', '支持的支付方式', 'setSandbox', '计算签名参数', '校验金额', '生成订单信息'],
        "function_count": 27,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/支付集成',
    },
    '数值工具': {
        "version": '1.0.0',
        "description": '大整数、定点数、高精度浮点、进制转换',
        "category": 'dev',
        "keywords": ['数值', '大整数', '定点数', '进制'],
        "dependencies": [],
        "functions": ['字符转数字', '数字转字符', '去除前导零', '比较绝对值', '加绝对值', '减绝对值', '乘绝对值', '大整数转为字符串', '大整数加', '大整数减', '大整数乘', '大整数比较', '大整数创建', '定点数转为字符串', '定点数加', '定点数减', '定点数乘', '定点数从分创建', '定点数创建', '十进制转二进制', '二进制转十进制', '十进制转十六进制', '十六进制转十进制', '十进制转八进制', '八进制转十进制', '进制转换'],
        "function_count": 26,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/数值工具',
    },
    '数值计算': {
        "version": '1.0.0',
        "description": '向量运算、矩阵、线性代数、插值、积分',
        "category": 'dev',
        "keywords": ['数值', '矩阵', '线性代数', '插值'],
        "dependencies": [],
        "functions": ['内部平方根', '向量点积', '向量加法', '向量减法', '向量模值', '向量归一化', '矩阵乘法', '矩阵转置', '行列式', '矩阵求逆', '线性插值', '梯形积分', '辛普森积分'],
        "function_count": 13,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/数值计算',
    },
    '数字签名': {
        "version": '1.0.0',
        "description": '数字签名算法',
        "category": 'security',
        "keywords": ['签名', '数字签名', 'ECDSA', 'DSA', '验证'],
        "dependencies": [],
        "functions": ['生成密钥对', '签名', '验证签名', '获取算法名称'],
        "function_count": 4,
        "ffi_count": 5,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/数字签名',
    },
    '数据可视化': {
        "version": '1.0.0',
        "description": '数据可视化库：热力图、箱线图、小提琴图、桑基图、树图、直方图、密度图',
        "category": 'dev',
        "keywords": ['数据可视化', '热力图', '箱线图', '小提琴图', '桑基图', '树图'],
        "dependencies": [],
        "functions": ['平方根', '绝对值', '取最大值', '取最小值', '排序列表副本', '求和', '平均值', '中位数', '标准差', '颜色插值', '生成颜色渐变', '生成SVG头', '生成SVG尾：', '生成标题', '生成图例', '生成网格线', '幂运算', '余弦', '正弦', '创建颜色方案', '创建主题', '计算箱线图数据', '计算直方图数据', '估计密度', '绘制热力图', '绘制箱线图', '绘制小提琴图', '绘制直方图', '绘制密度图', '绘制桑基图', '绘制树图', '布局递归', '绘制旭日图', '绘制递归', '绘制词云图', '绘制漏斗图', '绘制平行坐标图'],
        "function_count": 37,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/数据可视化',
    },
    '数据导入导出': {
        "version": '1.0.0',
        "description": '数据导入导出库：CSV/JSON/XML/YAML/Parquet/Excel/TSV/固定宽度读写',
        "category": 'dev',
        "keywords": ['数据导入', '数据导出', 'CSV', 'JSON', 'XML', 'Excel', 'Parquet'],
        "dependencies": [],
        "functions": ['创建读取选项', '创建写入选项', '读取CSV文本', '写入CSV文本', '读取TSV', '写入TSV', 'skip_whitespace', 'parse_json_string', 'parse_json_number', 'parse_json_bool', 'parse_json_null', 'parse_json_array', 'parse_json_object', 'parse_json_value', '读取JSON文本', 'json_to_string', '写入JSON文本', '读取JSON行', '写入JSON行', 'parse_xml', 'XMLNode_获取属性', 'XMLNode_获取子节点', 'XMLNode_获取所有子节点', 'XMLNode_获取文本', '读取XML文本', 'parse_yaml', '读取YAML文本', '写入YAML文本', '读取Excel', '读取Excel多工作表', '写入Excel', '创建工作簿', 'ExcelWorkbook_添加工作表', 'ExcelWorkbook_获取工作表', 'ExcelWorkbook_获取工作表名称列表', '读取固定宽度', '写入固定宽度', '读取INI', '写入INI', '读取属性文件', '写入属性文件', '读取Markdown表格', '写入Markdown表格', '检测文件格式', '检测CSV分隔符', '检测编码', '获取文件信息'],
        "function_count": 47,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/数据导入导出',
    },
    '数据库迁移': {
        "version": '1.0.0',
        "description": '数据库Schema版本管理：迁移脚本、版本追踪、升级回滚、校验和',
        "category": 'dev',
        "keywords": ['数据库', '迁移', '版本', 'Schema'],
        "dependencies": ['文件系统', '路径处理', '时间日期'],
        "functions": ['创建迁移器', '迁移器创建迁移', '迁移器升级', '迁移器回滚', '迁移器获取状态', '迁移器获取历史'],
        "function_count": 6,
        "ffi_count": 5,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/数据库迁移',
    },
    '数据框': {
        "version": '1.0.0',
        "description": '数据框库：DataFrame结构、列操作、过滤、分组、聚合、连接、透视表',
        "category": 'dev',
        "keywords": ['数据框', 'DataFrame', '列操作', '分组', '聚合', '连接'],
        "dependencies": [],
        "functions": ['calc_mean', 'calc_median', 'calc_stddev', 'calc_quantile', 'sort_list', 'dedup_list', 'sqrt_val', 'as_float', 'as_int', 'as_str', 'parse_csv', 'parse_query', 'infer_type', '创建数据框', '创建空数据框', '创建数据框从记录', '创建数据框从CSV', '创建数据列', 'DataFrame_获取列', 'DataFrame_设置列', 'DataFrame_删除列', 'DataFrame_重命名列', 'DataFrame_选择列', 'DataFrame_获取行', 'DataFrame_获取行列表', 'DataFrame_获取前N行', 'DataFrame_获取后N行', 'DataFrame_获取样本', 'DataFrame_获取形状', 'DataFrame_获取col_name', 'DataFrame_获取列类型', 'DataFrame_获取描述', 'DataFrame_获取信息', 'DataFrame_复制', 'DataFrame_清空', 'DataFrame_过滤', 'DataFrame_按列过滤', 'DataFrame_按值过滤', 'DataFrame_按值列表过滤', 'DataFrame_按范围过滤', 'DataFrame_按文本过滤', 'DataFrame_去重', 'DataFrame_丢弃空值', 'DataFrame_填充空值', 'DataFrame_查询', 'DataFrame_排序', 'DataFrame_排序多列', 'DataFrame_按索引排序', 'DataFrame_分组', 'GroupedDF_聚合', 'sum_list', 'GroupedDF_计数', 'GroupedDF_求和', 'GroupedDF_平均值', 'GroupedDF_最小值', 'GroupedDF_最大值', 'GroupedDF_标准差', 'GroupedDF_中位数', 'GroupedDF_应用', 'GroupedDF_获取分组', 'GroupedDF_获取分组键列表', 'GroupedDF_获取分组数', 'GroupedDF_转为数据框', 'DataFrame_内连接', 'DataFrame_左连接', 'DataFrame_右连接', 'DataFrame_外连接', 'DataFrame_交叉连接', 'DataFrame_半连接', 'DataFrame_反连接', 'DataFrame_透视', 'DataFrame_逆透视', 'DataFrame_滚动窗口', 'DataFrame_扩展窗口', 'DataFrame_排名', 'DataFrame_行号', 'DataFrame_滞后', 'DataFrame_前移', 'DataFrame_转为CSV', 'DataFrame_转为JSON', 'DataFrame_转为字典列表', 'DataFrame_转为Markdown', 'DataFrame_应用', 'DataFrame_应用多列', 'DataFrame_转换类型', 'DataFrame_映射值', 'DataFrame_替换值', 'DataFrame_剪切', 'DataFrame_标准化', 'DataFrame_标准化Z值'],
        "function_count": 90,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/数据框',
    },
    '数据清洗': {
        "version": '1.0.0',
        "description": '数据清洗库：缺失值处理、异常值检测、数据标准化、编码转换、特征工程',
        "category": 'dev',
        "keywords": ['数据清洗', '缺失值', '异常值', '标准化', '编码', '特征工程'],
        "dependencies": [],
        "functions": ['sqrt_val', 'abs_val', 'sort_list', 'sum_list', 'calc_mean', 'calc_median', 'calc_stddev', 'calc_mode', 'calc_min', 'calc_max', '检测缺失值', '检测缺失值比例', '移除缺失值', '移除缺失值按列', '填充缺失值', '填充缺失值均值', '填充缺失值中位数', '填充缺失值众数', '填充缺失值前向', '填充缺失值后向', '填充缺失值插值', '填充缺失值KNN', '检测异常值Z分数', '检测异常值IQR', '检测异常值百分位', '检测异常值孤立森林', '移除异常值', '截断异常值', '替换异常值', '标准化Z分数', '最小最大标准化', '鲁棒标准化', '最大绝对值标准化', '对数变换', 'BoxCox变换', '分位数变换', '二值化', '标签编码', '独热编码', '序号编码', '频率编码', '目标编码', '二进制编码', '哈希编码', '检测重复行', '移除重复行', '检测重复行按列', '模糊去重', '清理文本', '去除特殊字符', '去除HTML标签', '去除标点符号', '去除停用词', '文本标准化', '提取数字', '提取邮箱', '提取URL', '多项式特征', '交互特征', '分箱', '时间特征提取', '文本特征提取'],
        "function_count": 62,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/数据清洗',
    },
    '数据结构': {
        "version": '1.0.0',
        "description": '链表、栈、队列、堆、树、图、哈希表增强',
        "category": 'dev',
        "keywords": ['数据结构', '链表', '栈', '队列', '树', '图'],
        "dependencies": [],
        "functions": ['创建链表节点', '创建链表', '链表追加', '链表插入', '链表删除', '链表获取', '链表长度获取', '链表转为列表', '创建栈', '栈压入', '栈弹出', '栈窥视', '栈大小', '栈是否为空', '创建队列', '队列入队', '队列出队', '队列窥视', '队列大小', '队列是否为空', '创建最小堆', '堆上浮', '堆下沉', '堆插入', '堆弹出', '堆窥视', '堆是否为空', '创建树节点', '创建二叉树', '二叉树插入', '二叉树包含', '中序遍递归', '二叉树中序遍', '前序遍递归', '二叉树前序遍', '后序遍递归', '二叉树后序遍', '创建图', '图添加节点', '图添加边', '图邻居', '图节点数', '图边数', '图包含边', '创建哈希表增强', '哈希表设置', '哈希表获取', '哈希表删除', '哈希表包含', '哈希表键列表', '哈希表值列表', '哈希表条目列表'],
        "function_count": 52,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/数据结构',
    },
    '文件上传': {
        "version": '1.0.0',
        "description": '文件上传处理：多部分解析、断点续传、文件类型检测、大小限制、存储驱动',
        "category": 'dev',
        "keywords": ['文件上传', '多部分', '断点续传', '文件类型', '存储'],
        "dependencies": [],
        "functions": ['内部取时间戳', '内部包含', '范围', '内部分割', '内部转为小写', '内部整数转字符串', '内部字符串转整数', '内部下一个随机数', '内部随机字符串', '创建上传配置', '内部提取边界', '内部解析内容部署', '内部解析多部分头', '内部魔术字节检测', '内部生成唯一文件名', '检测文件类型', '检测文件类型从内容', '验证文件类型', '验证文件大小', '生成存储路径', '解析多部分', '解析多部分流式', '保存文件', '保存所有文件', '创建本地存储驱动', '创建内存存储驱动', '创建断点续传', '断点续传添加分块', '断点续传获取缺失分块', '断点续传是否完成', '断点续传合并分块', '断点续传获取进度'],
        "function_count": 32,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/文件上传',
    },
    '文件系统': {
        "version": '1.0.0',
        "description": '文件读写、目录遍历、权限管理、文件监控、临时文件',
        "category": 'dev',
        "keywords": ['文件', '目录', '权限', '遍历', '监控'],
        "dependencies": [],
        "functions": ['读取文件', '写入文件', '追加写入', '按行读取', '按字节读取', '文件是否存在', '文件大小', '删除文件', '重命名文件', '复制文件', '列出目录', '递归遍历', '创建目录', '删除目录', '获取权限', '检查可读', '检查可写', '检查可执行', '设置权限', '获取修改时间', '获取文件信息', '检查文件变更', '等待文件变更', '创建临时文件', '创建临时目录'],
        "function_count": 25,
        "ffi_count": 25,
        "has_source": True,
        "priority": 'P0',
        "stdlib_equivalent": '文件系统',
        "note": '已有 Python 实现，桥接到 stdlib',
        "path": 'packages/文件系统',
    },
    '文档格式': {
        "version": '1.0.0',
        "description": 'PDF生成、Office文档（OOXML）读写，底层绑定libharu/minizip',
        "category": 'dev',
        "keywords": ['PDF', 'DOCX', '生成', '文档', 'Office'],
        "dependencies": [],
        "functions": ['创建表格', '表格取列名', '表格取列', '表格取行', '表格行数', '表格列数', '表格转字典列表', '创建文件', '文件写入', '文件读取', '文件是否存在', '创建配置', '配置获取', '配置设置', '配置转字典', '创建Json', 'Json转字符串', 'Json序列化', 'Json转义字符串', 'Json获取', 'Json设置', '创建Xml', 'Xml转字符串', '创建Xml节点', 'Xml节点转字符串', '转义Xml', '创建Csv', 'Csv转字符串', '转义Csv', '创建Markdown', 'Markdown转字符串', 'Markdown添加文本', 'Markdown添加标题', 'Markdown添加无序列表', 'Markdown添加表格', 'Markdown文本', 'Markdown标题', 'Markdown无序列表', 'Markdown表格'],
        "function_count": 39,
        "ffi_count": 3,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/文档格式',
    },
    '文档生成': {
        "version": '1.0.0',
        "description": 'PDF、HTML、模板文档生成',
        "category": 'output',
        "keywords": ['文档', 'PDF', 'HTML', '模板', '生成'],
        "dependencies": [],
        "functions": [],
        "function_count": 0,
        "ffi_count": 14,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/文档生成',
    },
    '日志系统': {
        "version": '1.0.0',
        "description": '结构化日志系统：分级输出、文件轮转、JSON格式、自定义处理器',
        "category": 'dev',
        "keywords": ['日志', '调试', '分级', '轮转'],
        "dependencies": ['文件系统', '时间日期', '路径处理'],
        "functions": ['创建日志器', '日志器记录', '日志器调试', '日志器信息', '日志器警告', '日志器错误', '日志器设置级别', '日志器关闭'],
        "function_count": 8,
        "ffi_count": 7,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/日志系统',
    },
    '日期序列': {
        "version": '1.0.0',
        "description": '日期序列库：时间戳、时区、日期范围、重采样、偏移量、工作日历',
        "category": 'dev',
        "keywords": ['日期', '时间戳', '时区', '日期范围', '重采样', '工作日历'],
        "dependencies": [],
        "functions": ['创建时间戳', '创建时间戳从毫秒', '创建时间戳从字符串', '创建时间戳当前', '创建时间戳今天', 'ts格式化', 'tsToISO8601', 'tsToUnix', 'tsToMs', 'ts添加', 'ts减去', 'ts差值', 'tsIsBefore', 'tsIsAfter', 'tsIsEqual', 'ts获取星期', 'ts获取星期名称', 'ts获取月份名称', 'ts获取月份天数', 'ts是否闰年', 'tsIsWorkday', 'ts获取季度', 'ts获取周数', 'ts复制', 'ts设置时区', 'ts转为UTC', 'ts添加天数', 'ts添加小时', 'ts添加分钟', 'ts添加秒', 'ts添加月数', 'ts添加年数', '创建日期范围', '创建日期范围从数量', '创建工作日范围', 'dr获取时间戳列表', 'dr长度', 'dr包含', '创建持续时间', 'durToMs', 'dur总秒', 'dur总分钟', 'dur总小时', 'dur总天数', 'dur格式化', '创建时区', 'tz获取当前偏移', 'tzIsDST', '创建日期偏移', 'do应用', '创建重采样器', 'rs求和', 'rs平均值', 'rs最小值', 'rs最大值', 'rs首值', 'rs末值', 'rs计数', 'rs标准差', 'rs前向填充', 'rs后向填充', 'rs线性插值', 'rs应用'],
        "function_count": 63,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/日期序列',
    },
    '时间日期': {
        "version": '1.0.0',
        "description": '时间戳、时区、日历计算、定时器、格式化输出',
        "category": 'dev',
        "keywords": ['时间', '日期', '时区', '日历', '定时器', '格式化'],
        "dependencies": [],
        "functions": ['当前时间戳', '当前毫秒时间戳', '当前微秒时间戳', '当前时间', '当前UTC时间', '时间戳转日期时间', '时间戳转UTC', '日期时间转时间戳', '创建日期时间', '创建UTC日期时间', '格式化时间', '格式化ISO8601', '格式化RFC3339', '格式化中文日期', '解析时间', '获取星期名称', '获取月份名称', '获取月份天数', '是闰年', '获取星期', '获取年日', '时间相加', '时间相减', '时间加天数', '时间加小时', '时间加分钟', '时间比较', '时间等于', '时间早于', '创建时间间隔', '时间间隔总秒数', '时间间隔总毫秒数', '时间间隔天数', '时间间隔小时数', '时间间隔分钟数', '开始计时', '结束计时', '休眠', '毫秒休眠'],
        "function_count": 39,
        "ffi_count": 12,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/时间日期',
    },
    '构建工具': {
        "version": '1.0.0',
        "description": '编译缓存、增量构建、跨平台编译',
        "category": 'dev',
        "keywords": ['构建', '编译', '缓存', '增量', '跨平台'],
        "dependencies": [],
        "functions": [],
        "function_count": 0,
        "ffi_count": 13,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/构建工具',
    },
    '模板渲染': {
        "version": '1.0.0',
        "description": '服务端模板引擎：布局继承、局部模板、过滤器、缓存、自动转义',
        "category": 'dev',
        "keywords": ['模板', '渲染', '布局', '继承', '过滤器'],
        "dependencies": [],
        "functions": ['范围', '整数转字符串', '内部包含', '内部以开始', '内部分割字符串', '内部去除空白', '内部转为小写', '内部转为大写', '内部查找字符', '内部值转字符串', '内部HTML转义', '内部HTML反转义', '内部替换所有', '内部URL编码', '内部转为大写过滤器', '内部转为小写过滤器', '内部首字母大写过滤器', '内部截断过滤器', '内部默认值过滤器', '内部去除空白过滤器', '内部JSON编码过滤器', '内部URL编码过滤器', '内部HTML转义过滤器', '内部换行转BR过滤器', '内部数字格式化过滤器', 'engineRegisterFilter', 'engineRegisterGlobal', 'engineRender', 'engineRenderString', 'engineClearCache', 'renderTemplateContent', 'renderRawBlock', 'renderComments', 'renderExtendsBlock', 'extractBlockDefs', 'renderBlockDefs', 'renderIncludeBlock', 'renderIfBlock', 'renderForBlock', 'renderVariables', 'findBlockEnd', 'findBlockInString', 'evaluateCondition', 'evaluateSimpleCondition', '创建tpl引擎'],
        "function_count": 45,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/模板渲染',
    },
    '正则表达式': {
        "version": '1.0.0',
        "description": 'PCRE兼容的正则匹配、替换、捕获组，基于PCRE2',
        "category": 'dev',
        "keywords": ['正则', '匹配', '替换', 'PCRE2'],
        "dependencies": [],
        "functions": ['MatchResultGroup', 'RegexObjNew', 'RegexObjIsMatch', 'RegexObjSearch', 'RegexObjSearchAll', 'RegexObjReplace', 'RegexObjSplit', 'RegexObjFree'],
        "function_count": 8,
        "ffi_count": 8,
        "has_source": True,
        "priority": 'P0',
        "stdlib_equivalent": '正则表达式',
        "note": '已有 Python 实现，桥接到 stdlib',
        "path": 'packages/正则表达式',
    },
    '测试框架增强': {
        "version": '1.0.0',
        "description": '参数化测试、Mock、快照测试、基准测试',
        "category": 'dev',
        "keywords": ['测试', '参数化', 'Mock', '快照', '基准'],
        "dependencies": [],
        "functions": [],
        "function_count": 0,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/测试框架增强',
    },
    '消息队列': {
        "version": '1.0.0',
        "description": '发布/订阅、消息代理、队列系统',
        "category": 'infrastructure',
        "keywords": ['消息', '队列', '发布', '订阅', '代理'],
        "dependencies": [],
        "functions": [],
        "function_count": 0,
        "ffi_count": 17,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/消息队列',
    },
    '游戏引擎绑定': {
        "version": '1.0.0',
        "description": '游戏引擎基础绑定：窗口管理、输入事件、渲染器、资源管理、碰撞检测',
        "category": 'dev',
        "keywords": ['游戏引擎', '窗口', '输入', '渲染', '资源管理', '碰撞检测'],
        "dependencies": [],
        "functions": ['createGameWindow', 'gameWindow_show', 'gameWindow_hide', 'gameWindow_close', 'gameWindow_setTitle', 'gameWindow_setSize', 'gameWindow_setPosition', 'gameWindow_setFullscreen', 'gameWindow_setResizable', 'gameWindow_centerScreen', 'gameWindow_processEvent', 'gameWindow_pollEvents', 'gameWindow_bindEvent', 'gameWindow_getEventQueue', 'gameWindow_clearEventQueue', 'gameWindow_isClosed', 'gameWindow_swapBuffers', 'gameWindow_getSize', 'gameWindow_getPosition', 'keyIsPressed', 'keyGetPressTime', 'keySetRepeat', 'mouseGetPosition', 'mouseButtonIsPressed', 'mouseSetCursor', 'mouseSetCapture', 'mouseSetVisible', 'gameWindow_updateKeyboard', 'gameWindow_updateMouse', 'createRenderer', 'rendererInitialize', 'rendererDestroy', 'rendererClear', 'rendererSetClearColor', 'rendererSetViewport', 'rendererEnableDepthTest', 'rendererEnableBlend', 'rendererCreateTexture', 'rendererBindTexture', 'rendererDeleteTexture', 'rendererDrawMesh', 'rendererDrawArray', 'rendererDrawElements', 'rendererDrawRect', 'rendererDrawLine', 'rendererDrawSprite', 'rendererDrawText', 'rendererPresent', 'createSprite', 'spriteSetPosition', 'spriteSetRotation', 'spriteSetScale', 'spriteSetFrame', 'spriteGetRect', 'spriteCheckCollision', 'createSpriteSheet', 'spriteSheetGetFrame', 'createAnimation', 'animationUpdate', 'animationPlay', 'animationStop', 'animationPause', 'animationGetCurrentFrame', 'animationIsFinished', 'createCamera', 'cameraMove', 'cameraRotate', 'cameraZoom', 'cameraWorldToScreen', 'cameraScreenToWorld', 'cameraUpdateProjection', 'cameraSetOrthographic', 'cameraSetPerspective', 'createAABB', 'createCircle', 'createOBB', 'collisionAABBvsAABB', 'collisionCirclevsCircle', 'collisionAABBvsCircle', 'collisionPointvsAABB', 'collisionPointvsCircle', 'findClosestCollision', 'calculateCollisionResponse', 'getCollisionResult', 'satSeparateAxis', 'createResourceMgr', 'resourceMgrLoad', 'resourceMgrUnload', 'resourceMgrGet', 'resourceMgrIsLoaded', 'resourceMgrClearCache', 'resourceMgrGetTotalSize', 'resourceMgrPreload', 'sqrt', 'getCurrentTime'],
        "function_count": 95,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/游戏引擎绑定',
    },
    '环境变量': {
        "version": '1.0.0',
        "description": '读取、设置、遍历环境变量，.env文件解析',
        "category": 'dev',
        "keywords": ['环境变量', 'env', '配置', 'dotenv'],
        "dependencies": [],
        "functions": ['获取环境变量', '设置环境变量', '删除环境变量', '环境变量是否存在', '列出全部环境变量', '获取环境变量或抛出', '展开环境变量', '解析env文本', '解析env文件', '加载env文件', '获取环境变量整数', '获取环境变量布尔', '获取环境变量列表', '环境变量到字符串', '范围'],
        "function_count": 15,
        "ffi_count": 9,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/环境变量',
    },
    '短信': {
        "version": '1.0.0',
        "description": '短信网关：短信API、模板发送、批量发送、状态查询、签名管理',
        "category": 'dev',
        "keywords": ['短信', '短信API', '模板发送', '批量发送', '状态查询'],
        "dependencies": [],
        "functions": ['创建阿里云短信配置', '创建腾讯云短信配置', '创建阿里云短信配置沙盒', '创建短信模板请求', '发送短信', '发送短信批量', '发送短信模板', '查询短信状态', '查询短信统计', '获取模板列表', '获取签名列表', '添加模板', '删除模板', '添加签名', '删除签名', '查询模板审核状态', '查询签名审核状态', '生成请求URL', '签名请求', '阿里云短信签名', '腾讯云短信签名', '解析发送响应', '解析查询响应', '是否发送成功', '获取失败号码列表', '获取成功消息ID列表', '格式化模板', '验证手机号格式', '清理手机号', '批量拆分'],
        "function_count": 30,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/短信',
    },
    '科学计算': {
        "version": '1.0.0',
        "description": '科学计算库：矩阵运算、线性代数、微积分、优化算法、插值、积分',
        "category": 'dev',
        "keywords": ['科学计算', '矩阵', '线性代数', '微积分', '优化', '插值'],
        "dependencies": [],
        "functions": ['创建矩阵', '创建矩阵从列表', '创建单位矩阵', '创建零矩阵', '创建对角矩阵', '创建随机矩阵', 'mat_get', 'mat_set', 'mat_getRow', 'mat_getCol', 'mat_getDiag', 'mat_shape', 'mat_copy', 'mat_toList', 'mat_transpose', 'mat_invert', 'mat_determinant', 'mat_trace', 'mat_rank', 'mat_norm', 'mat_cond', 'mat_pow', '矩阵加法', '矩阵减法', '矩阵乘法', '矩阵数乘', '矩阵点乘', '创建向量', 'vec_dot', 'vec_cross', 'vec_norm', 'vec_normalize', 'vec_angle', '求解线性方程组', 'LU分解', 'QR分解', '特征值', '特征向量', '奇异值分解', '乔列斯基分解', '最小二乘', '数值微分', '数值梯度', '数值hessMat', '数值积分', '自适应积分', '二重积分', '常微分方程', '牛顿法', '黄金分割搜索', '随机搜索', '模拟退火', '创建线性插值器', '创建拉格朗日插值器', '创建样条插值器', 'interp_interp', 'interp_batchInterp', '阶乘', '二项式系数', '斐波那契', '伽马函数', '贝塔函数', '误差函数', '互补误差函数'],
        "function_count": 64,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/科学计算',
    },
    '第三方登录': {
        "version": '1.0.0',
        "description": '第三方登录：OAuth2.0、微信/支付宝/QQ/GitHub/Google登录、回调处理、用户信息获取',
        "category": 'dev',
        "keywords": ['第三方登录', 'OAuth2', '微信登录', '支付宝登录', 'QQ登录'],
        "dependencies": [],
        "functions": ['获取微信提供商', '获取支付宝提供商', '获取QQ提供商', '获取GitHub提供商', '获取Google提供商', '创建OAuth配置', '生成授权URL', '生成授权URLPKCE', '交换代码获取令牌', '刷新令牌', '撤销令牌', '获取用户信息', '验证状态', '解析回调请求', '创建代码挑战', '生成代码Verifier', '计算代码挑战S256', '微信登录生成URL', '微信登录获取令牌', '微信登录获取用户信息', '支付宝登录生成URL', '支付宝登录获取令牌', '支付宝登录获取用户信息', 'QQ登录生成URL', 'QQ登录获取令牌', 'QQ登录获取用户信息', 'GitHub登录生成URL', 'GitHub登录获取令牌', 'GitHub登录获取用户信息', 'Google登录生成URL', 'Google登录获取令牌', 'Google登录获取用户信息', '签名请求', '生成随机状态', '解析JSON用户信息', '检查令牌是否过期', '是否需要刷新'],
        "function_count": 37,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/第三方登录',
    },
    '算法工具': {
        "version": '1.0.0',
        "description": '动态规划、回溯、贪心、图算法（最短路径、最小生成树）',
        "category": 'dev',
        "keywords": ['算法', '动态规划', '图', '回溯'],
        "dependencies": [],
        "functions": ['创建优先队列', '优先队列上浮', '优先队列下沉', '优先队列插入', '优先队列弹出', '优先队列是否为空', '并查集查找', '并查集合并', '背包问题', '最长公共子序列', '全排列', '全排列回溯', '子集', '子集回溯', 'Dijkstra', '最小生成树', '按权重排', '贪心找零', '降序排'],
        "function_count": 19,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/算法工具',
    },
    '类型工具': {
        "version": '1.0.0',
        "description": '运行时类型检查、泛型约束、类型转换、可空类型',
        "category": 'dev',
        "keywords": ['类型', '运行时', '检查', '可空'],
        "dependencies": [],
        "functions": ['获取数字字符映射', '获取数字到字符', '型别检查', '是整数', '是浮点数', '是字符串', '是布尔', '是列表', '是字典', '是空', '转整数', '字符串转整数', '转浮点数', '字符串转浮点数', '转字符串', '整数转字符串', '浮点数转字符串', '转布尔', '可空', '可空_有值', '可空_取值', '可空_或缺省', '可空_或计算', '型别配'],
        "function_count": 24,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/类型工具',
    },
    '系统信息': {
        "version": '1.0.0',
        "description": 'CPU、内存、磁盘、网络接口信息获取',
        "category": 'dev',
        "keywords": ['系统', 'CPU', '内存', '磁盘', '网络', '监控'],
        "dependencies": [],
        "functions": ['获取CPU信息', '获取CPU核心数', '获取CPU使用率', '获取CPU每核使用率', '获取内存信息', '获取内存总量', '获取内存可用', '获取内存使用率', '获取磁盘信息', '获取磁盘全部', '获取所有磁盘信息', '获取网口全部', '获取网络接口信息', '获取所有网络接口信息', '获取系统概览', '获取主机名', '获取操作系统名称', '获取操作系统版本', '获取系统架构', '获取当前用户', '获取启动时间', '获取运行时间', '格式化字节', '格式化运行时间'],
        "function_count": 24,
        "ffi_count": 29,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/系统信息',
    },
    '系统托盘': {
        "version": '1.0.0',
        "description": '系统托盘管理：托盘图标、右键菜单、气泡通知、事件处理',
        "category": 'dev',
        "keywords": ['系统托盘', '通知', '图标', '菜单', '气泡提示'],
        "dependencies": [],
        "functions": ['createTray', 'tray_show', 'tray_hide', 'tray_setIcon', 'tray_setTooltip', 'tray_setMenu', 'tray_addMenuItem', 'tray_removeMenuItem', 'tray_updateMenuItem', 'tray_showNotification', 'tray_showNotificationSimple', 'tray_closeNotification', 'tray_closeAllNotifications', 'tray_getNotificationList', 'tray_getUnreadCount', 'tray_bindEvent', 'tray_unbindEvent', 'tray_triggerEvent', 'tray_popup', 'tray_getStatus', 'tray_destroy', 'createMenuItem', 'menuItem_addSubmenu', 'menuItem_setSeparator', 'menuItem_setEnabled', 'menuItem_setChecked', 'createNotification'],
        "function_count": 27,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/系统托盘',
    },
    '线程': {
        "version": '1.0.0',
        "description": '线程创建、同步原语（互斥锁、信号量、条件变量）、线程池',
        "category": 'dev',
        "keywords": ['线程', '互斥锁', '信号量', '条件变量', '线程池', '同步'],
        "dependencies": [],
        "functions": ['创建线程', '等待线程', '分离线程', '获取线程号', '当前线程号', '线程休眠', '线程让出', '创建互斥锁', '互斥锁锁定', '互斥锁尝试锁定', '互斥锁解锁', '互斥锁销毁', '创建信号量', '信号量阻塞', '信号量发布', '信号量销毁', '创建条件变量', '条件变量阻塞', '条件变量通知', '条件变量通知全部', '条件变量销毁', '原子加法', '原子减法', '原子存储', '原子加载', '原子比较交换', '线程池工作线程', '创建线程池', '线程池提交任务', '线程池等待全部', '线程池关停'],
        "function_count": 31,
        "ffi_count": 26,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/线程',
    },
    '统计分析': {
        "version": '1.0.0',
        "description": '统计分析库：描述统计、概率分布、假设检验、回归分析、方差分析',
        "category": 'dev',
        "keywords": ['统计', '概率', '分布', '假设检验', '回归', '方差分析'],
        "dependencies": [],
        "functions": ['求平均值', '求中位数', '求众数', '求标准差', '求方差', '求偏度', '求峰度', '求分位数', '求比例分位数', '求极差', '求四分位距', '求协方差', '求相关系数', '阶乘', '伽马函数', '贝塔函数', '误差函数', '标准正态CDF', '标准正态分位数', '指数', 'tDistCDF', '卡方CDF', '矩阵转置', '矩阵乘法', '矩阵求逆', '求解线性方程组', '列表排序', '列表和', '列表平方和', '平方根', '描述统计', '列表去重计数', '描述统计多列', '频率分布', '交叉表', '计算协方差', '计算相关系数', '计算斯皮尔曼相关系数', '计算肯德尔相关系数', '相关矩阵', '协方差矩阵', '正态PDF', '正态CDF', '正态PPF', '正态分布', '标准正态分布', '均匀分布', '均匀分布PDF', '均匀分布CDF', '指数分布', '指数分布PDF', '指数分布CDF', '二项分布', '对数', '泊松分布', 'tDist', 'fDist', '卡方分布', '概率分布PDF', '概率分布CDF', '概率分布分位数', '概率分布随机抽样', '计算效应量', 'tTestOneSample', 'tTestTwoSample', 'tTestPaired', '卡方检验', '卡方独立性检验', 'fTest', '曼惠特尼U检验', '威尔科克森检验', '柯尔莫哥洛夫检验', '正态性检验', '二项检验', '线性回归', '多元线性回归', '多项式回归', '逻辑回归', '回归结果预测', '回归结果预测区间', '回归结果残差', '回归结果残差图数据', '回归结果摘要', '单因素方差分析', '双因素方差分析', '重复测量方差分析', '方差分析事后检验', '计算置信区间', '计算统计检验力', '计算样本量', '标准化数据', '最小最大标准化'],
        "function_count": 92,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/统计分析',
    },
    '缓存系统': {
        "version": '1.0.0',
        "description": '多级缓存（内存/Redis/文件），LRU/LFU/TTL淘汰策略',
        "category": 'database',
        "keywords": ['缓存', 'LRU', 'LFU', 'TTL', '多级', '淘汰'],
        "dependencies": [],
        "functions": ['新建缓存配置', '新建内存缓存', '缓存获取', '缓存设置', '缓存删除', '缓存是否存在', '缓存清空', '缓存获取统计', '缓存获取大小'],
        "function_count": 9,
        "ffi_count": 9,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/缓存系统',
    },
    '网络工具': {
        "version": '1.0.0',
        "description": 'IP地址处理、子网计算、端口扫描、Ping',
        "category": 'net',
        "keywords": ['IP', '子网', '端口', '扫描', 'Ping', '网络'],
        "dependencies": ['Socket'],
        "functions": ['内部2的幂', '内部获取掩码整数', '内部包含', '内部分割', '内部是否全数字', '内部字符串转整数', '内部整数转字符串', '解析IPv4', '地址转字符串', '地址转整数', '整数转地址', '验证IPv4', '验证IPv6', '获取本地IP列表', '是私有IP', '是回环IP', '是广播IP', '是组播IP', '创建子网', '解析CIDR', '子网包含IP', '子网分割', '获取子网掩码', '前缀长度到掩码', '掩码到前缀长度', '扫描端口', '扫描端口范围', '扫描常用端口', '获取常用服务名称', 'Ping主机', 'Ping主机多次', '获取主机名', '获取主机名地址', '检查网络连通性', 'Traceroute追踪'],
        "function_count": 35,
        "ffi_count": 3,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/网络工具',
    },
    '视频处理': {
        "version": '1.0.0',
        "description": '视频处理库：帧提取、视频信息、缩略图、简单转码、时间轴操作',
        "category": 'dev',
        "keywords": ['视频处理', '帧提取', '视频信息', '缩略图', '转码'],
        "dependencies": [],
        "functions": ['获取视频信息', '获取视频信息从数据', '提取帧', '提取帧时间', '提取帧批量', '提取缩略图', '提取缩略图网格', '创建视频帧', '视频帧调整大小', '视频帧裁剪', '视频帧添加水印', '视频帧添加文字', '视频帧转为灰度', '视频帧调整亮度', '视频帧调整对比度', '视频帧复制', '创建视频配置', '创建时间轴', '时间轴添加片段', '时间轴移除片段', '时间轴添加效果', '时间轴添加过渡', '时间轴获取当前片段', '时间轴获取持续时间', '时间轴分割片段', '时间轴合并片段', '时间轴移动片段', '计算帧索引', '计算帧时间', '格式化时间', '解析时间', '时间码转帧索引', '帧索引转时间码', '视频转码', '视频裁剪', '视频拼接', '视频缩放', '视频旋转', '视频提取音频', '视频替换音频', '视频静音', '视频加速', '视频添加水印', '视频生成缩略图', '获取支持的格式', '获取支持的编解码器', '检测视频格式', '视频信息格式化持续时间', '视频信息格式化文件大小', '视频信息格式化摘要'],
        "function_count": 50,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/视频处理',
    },
    '认证授权': {
        "version": '1.0.0',
        "description": 'RBAC/ABAC权限控制、OAuth2.0/OIDC认证、JWT令牌、API密钥、MFA/TOTP、审计日志',
        "category": 'dev',
        "keywords": ['认证', '授权', 'RBAC', 'OAuth', 'JWT', 'MFA', '安全'],
        "dependencies": [],
        "functions": [],
        "function_count": 0,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/认证授权',
    },
    '证书': {
        "version": '1.0.0',
        "description": 'X.509证书解析/验证/生成，CSR生成，证书链验证，CRL检查',
        "category": 'dev',
        "keywords": ['证书', 'X509', 'SSL', 'TLS', 'PKI', '安全'],
        "dependencies": [],
        "functions": ['解析证书', '解析证书DER', 'cert_get_subject', 'cert_get_issuer', 'cert_get_serial', 'cert_get_validity', 'cert_get_fingerprint', 'cert_get_pub_key', 'cert_get_pub_key_algo', 'cert_get_sig_algo', 'cert_get_version', 'cert_get_raw_pem', 'cert_is_self_signed', 'cert_is_expired', 'cert_days_left', 'cert_verify', '生成自签名证书', '生成密钥对', '生成CSR', 'csr_get_raw_pem', 'csr_get_subject', 'csr_get_pub_pem', '检查CRL', '加载CRL', 'cert_pem_to_der', 'PEM转DER', 'DER转PEM', 'verify_is_valid', 'verify_get_err', 'verify_get_chain_depth', 'verify_get_verify_path', 'crl_is_revoked', 'crl_get_revoke_date', 'crl_get_revoke_reason', 'crl_get_err', '释放证书'],
        "function_count": 36,
        "ffi_count": 25,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/证书',
    },
    '请求验证': {
        "version": '1.0.0',
        "description": '请求体校验：JSON Schema验证、参数类型转换、自定义规则、嵌套对象验证',
        "category": 'dev',
        "keywords": ['验证', '校验', 'JSON Schema', '参数', '类型转换'],
        "dependencies": [],
        "functions": ['内部范围', '内部整数转字符串', '内部包含', '内部以开始', '内部分割', '内部字符串转整数', '内部查找字符', '内部是整数', '内部是浮点数', '内部键列表', '必填规则', '最小长度规则', '最大长度规则', '长度范围规则', '最小值规则', '最大值规则', '数值范围规则', '正则规则', '邮箱规则', '地址URL规则', '手机号规则', '身份证号规则', 'IP地址规则', '在列表中规则', '整数规则', '浮点数规则', '布尔值规则', '自定义规则', '可空规则', '默认值规则', '转为整数', '转为浮点数', '转为布尔', '转为字符串', '创建验证模式', '创建验证规则', '验证模式验证', '验证单个规则', '验证模式验证部分', '验证模式消毒', '内部验证邮箱格式', '内部验证URL格式', '内部验证手机号', '内部验证身份证号', '内部验证IP地址', '内部简单模式测试', '内部完全对应'],
        "function_count": 47,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/请求验证',
    },
    '调试器': {
        "version": '1.0.0',
        "description": '断点、单步执行、变量检查、调用栈追踪',
        "category": 'dev',
        "keywords": ['调试', '断点', '单步', '调用栈', '变量'],
        "dependencies": [],
        "functions": [],
        "function_count": 0,
        "ffi_count": 17,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/调试器',
    },
    '路径处理': {
        "version": '1.0.0',
        "description": '跨平台路径操作：拼接、解析、规范化、Glob匹配',
        "category": 'dev',
        "keywords": ['路径', '拼接', '解析', 'Glob', '规范化'],
        "dependencies": [],
        "functions": ['绝对路径', '相对路径', '拼接路径', '拼接路径2', '获取文件名', '获取目录名', '获取扩展名', '获取基础名', '获取父目录', '分割路径', '分割扩展名', '分割全部', '规范化路径', '获取相对路径', 'globMatch', '路径是否相等', '更改扩展名', '主目录', '当前目录', '临时目录'],
        "function_count": 20,
        "ffi_count": 3,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/路径处理',
    },
    '路由': {
        "version": '1.0.0',
        "description": '高性能URL路由：Trie树匹配、路径参数、正则匹配、路由分组、中间件链',
        "category": 'dev',
        "keywords": ['路由', 'URL', '路径参数', '正则', '分组'],
        "dependencies": [],
        "functions": ['内部分割', '内部包含', '内部以开始', '内部范围', '内部整数转字符串', '内部分割路径', '内部提取规则', '内部提取参数名', '内部查找字符', '内部查找子节点', '内部查找精确子节点', '内部简单对应', '内部完全对应', '内部尝试对应', '创建路由器：', '路由器注册', '路由器对应', '路由器分组', '分组路由器注册', '分组路由器再分组', '分组路由器使用中间件', '路由器使用中间件', '路由器使用路由中间件', '路由器设置404', '路由器设置405', '路由器获取路由列表'],
        "function_count": 26,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/路由',
    },
    '进程管理': {
        "version": '1.0.0',
        "description": '启动进程、管道通信、获取退出码、进程树管理',
        "category": 'dev',
        "keywords": ['进程', '管道', '退出码', '子进程'],
        "dependencies": [],
        "functions": ['启动进程', '等待进程', '终止进程', '进程是否运行中', '获取进程退出码', '获取进程ID', '获取标准输出', '获取标准错误', '写入标准输入', '关闭标准输入', '执行命令', '执行命令并获取输出', '执行命令并检查', '获取当前进程ID', '列出子进程', '系统休眠'],
        "function_count": 16,
        "ffi_count": 14,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/进程管理',
    },
    '连接池': {
        "version": '1.0.0',
        "description": '数据库连接池，连接复用、健康检查、超时管理',
        "category": 'database',
        "keywords": ['连接池', '复用', '健康检查', '超时', '连接'],
        "dependencies": [],
        "functions": ['创建连接池', '连接池获取连接', '连接池释放连接', '连接池关闭', '连接池获取统计', '连接池设置最小连接数'],
        "function_count": 6,
        "ffi_count": 6,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/连接池',
    },
    '迭代器工具': {
        "version": '1.0.0',
        "description": '懒迭代器：链式、压缩、无限序列、窗口滑动、分块迭代',
        "category": 'dev',
        "keywords": ['迭代器', '懒加载', '流式', '工具'],
        "dependencies": ['集合扩展'],
        "functions": [],
        "function_count": 0,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/迭代器工具',
    },
    '邮件': {
        "version": '1.0.0',
        "description": '邮件库：SMTP客户端、邮件格式解析、HTML邮件、附件支持、TLS加密',
        "category": 'dev',
        "keywords": ['邮件', 'SMTP', 'HTML邮件', '附件', 'TLS'],
        "dependencies": [],
        "functions": ['创建邮件地址', '创建邮件', '创建SMTP配置', '格式化日期', '验证邮件地址', '提取邮件地址', '解析邮件', '解析HTML内容', '解析文本内容', '获取所有附件', '获取附件内容', '发送邮件', '发送邮件批量', '生成MIME'],
        "function_count": 14,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/邮件',
    },
    '错误处理': {
        "version": '1.0.0',
        "description": '错误链、Result类型、错误上下文、Panic钩子',
        "category": 'dev',
        "keywords": ['错误', 'Result', '错误链', '异常'],
        "dependencies": [],
        "functions": ['创建错误', '包装错误', '错误链_获取', '结果成功', '结果失败', '是成功_检查', '是失败_检查', '取值_获取', '或默认_获取', '错误消息_获取', '然后_链式', '设置Panic钩子', '触发Panic', '恢复Panic钩子'],
        "function_count": 14,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/错误处理',
    },
    '随机数': {
        "version": '1.0.0',
        "description": '伪随机、分布采样、随机种子管理',
        "category": 'dev',
        "keywords": ['随机', '伪随机', '安全', '采样'],
        "dependencies": [],
        "functions": ['设置种子', '随机整数', '随机浮点数', '随机选择', '随机打乱', '均匀采样', '正态采样'],
        "function_count": 7,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/随机数',
    },
    '集合扩展': {
        "version": '1.0.0',
        "description": '列表、字典、集合的增强操作：排序、过滤、映射、分组、去重',
        "category": 'dev',
        "keywords": ['集合', '列表', '字典', '工具'],
        "dependencies": [],
        "functions": ['列表_排序', '列表_过滤', '列表_映射', '列表_去重', '列表_分组', '列表_分块', '列表_扁平化', '列表_复制', '字典_合并', '字典_获取键组', '字典_获取值组', '字典_过滤', '集合_交集', '集合_并集', '集合_差集'],
        "function_count": 15,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/集合扩展',
    },
    '静态分析': {
        "version": '1.0.0',
        "description": 'Linter、代码规范检查、死代码检测',
        "category": 'dev',
        "keywords": ['静态分析', 'Linter', '规范', '死代码', '质量'],
        "dependencies": [],
        "functions": ['分析文件', '检查代码规范', '检测死代码', '获取分析统计', '获取问题列表', '获取分数'],
        "function_count": 6,
        "ffi_count": 5,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/静态分析',
    },
    '非对称加密': {
        "version": '1.0.0',
        "description": 'RSA/ECDSA/Ed25519非对称加密，密钥生成/导入导出，签名/验签，数字信封',
        "category": 'dev',
        "keywords": ['加密', 'RSA', 'ECDSA', 'Ed25519', '签名', '非对称'],
        "dependencies": [],
        "functions": ['gen_rsa_keypair', 'rsa_enc', 'rsa_dec', 'rsa_sign', 'rsa_verify', 'gen_ecdsa_keypair', 'ecdsa_sign', 'ecdsa_verify', 'gen_ed25519_keypair', 'ed25519_sign', 'ed25519_verify', 'export_pub', 'export_priv', 'import_from_pem', 'pem_to_der', 'der_to_pem', 'envelope_enc', 'envelope_dec', 'get_algo', 'get_bits', 'has_priv', 'has_pub'],
        "function_count": 22,
        "ffi_count": 15,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/非对称加密',
    },
    '音频处理': {
        "version": '1.0.0',
        "description": '音频处理库：WAV解析、FFT频谱、滤波、重采样、合成、效果器',
        "category": 'dev',
        "keywords": ['音频处理', 'WAV', 'FFT', '频谱', '滤波', '合成'],
        "dependencies": [],
        "functions": [],
        "function_count": 0,
        "ffi_count": 0,
        "has_source": True,
        "priority": 'P2',
        "stdlib_equivalent": None,
        "note": '',
        "path": 'packages/音频处理',
    },
}

# 按分类分组
CATEGORIES = {
    'database': ['NoSQL连接器', 'SQLite', '缓存系统', '连接池'],
    'dev': ['2D绘图', 'AI推理', 'API文档', 'Actor模型', 'CSV', 'GUI框架', 'JSON', 'Markdown', 'RPC框架', 'Redis绑定', 'TOML', 'Web框架', 'XML', 'YAML', '中间件集合', '二进制编码', '云存储', '代码格式化', '任务队列', '全文搜索', '内存管理', '包管理增强', '协程', '压缩算法', '命令行参数', '哈希', '图像处理增强', '图像编解码', '图表', '地理计算', '字体渲染', '字符串处理', '密码哈希', '对称加密', '对话框', '对象存储', '并行计算', '异步运行时', '性能分析', '排序与搜索', '控件库', '支付集成', '数值工具', '数值计算', '数据可视化', '数据导入导出', '数据库迁移', '数据框', '数据清洗', '数据结构', '文件上传', '文件系统', '文档格式', '日志系统', '日期序列', '时间日期', '构建工具', '模板渲染', '正则表达式', '测试框架增强', '游戏引擎绑定', '环境变量', '短信', '科学计算', '第三方登录', '算法工具', '类型工具', '系统信息', '系统托盘', '线程', '统计分析', '视频处理', '认证授权', '证书', '请求验证', '调试器', '路径处理', '路由', '进程管理', '迭代器工具', '邮件', '错误处理', '随机数', '集合扩展', '静态分析', '非对称加密', '音频处理'],
    'graphics': ['图形渲染'],
    'infrastructure': ['消息队列'],
    'language': ['事件驱动', '响应式编程'],
    'media': ['图像处理'],
    'net': ['DNS', 'HTTP客户端', 'HTTP服务端', 'Socket', 'URL解析', 'WebSocket', '网络工具'],
    'output': ['文档生成'],
    'security': ['JWT', 'OAuth客户端', '加密算法', '哈希算法', '数字签名'],
}

# 按优先级分组 (P0=高频已有stdlib/P1=高频需新建/P2=其他)
PRIORITY = {
    'P0': ['CSV', 'JSON', '文件系统', '正则表达式'],
    'P1': ['HTTP客户端', 'SQLite', 'Socket'],
    'P2': ['2D绘图', 'AI推理', 'API文档', 'Actor模型', 'DNS', 'GUI框架', 'HTTP服务端', 'JWT', 'Markdown', 'NoSQL连接器', 'OAuth客户端', 'RPC框架', 'Redis绑定', 'TOML', 'URL解析', 'WebSocket', 'Web框架', 'XML', 'YAML', '中间件集合', '事件驱动', '二进制编码', '云存储', '代码格式化', '任务队列', '全文搜索', '内存管理', '加密算法', '包管理增强', '协程', '压缩算法', '命令行参数', '哈希', '哈希算法', '响应式编程', '图像处理', '图像处理增强', '图像编解码', '图形渲染', '图表', '地理计算', '字体渲染', '字符串处理', '密码哈希', '对称加密', '对话框', '对象存储', '并行计算', '异步运行时', '性能分析', '排序与搜索', '控件库', '支付集成', '数值工具', '数值计算', '数字签名', '数据可视化', '数据导入导出', '数据库迁移', '数据框', '数据清洗', '数据结构', '文件上传', '文档格式', '文档生成', '日志系统', '日期序列', '时间日期', '构建工具', '模板渲染', '测试框架增强', '消息队列', '游戏引擎绑定', '环境变量', '短信', '科学计算', '第三方登录', '算法工具', '类型工具', '系统信息', '系统托盘', '线程', '统计分析', '缓存系统', '网络工具', '视频处理', '认证授权', '证书', '请求验证', '调试器', '路径处理', '路由', '进程管理', '连接池', '迭代器工具', '邮件', '错误处理', '随机数', '集合扩展', '静态分析', '非对称加密', '音频处理'],
}

# 导入名 -> lightpub 包名映射
# 光明代码可用 "导入 标准文件系统" 或 "导入 文件系统" 访问
IMPORT_MAP = {
    '2D绘图': '2D绘图',  # 直接名
    '标准2D绘图': '2D绘图',  # 标准前缀
    'Actor模型': 'Actor模型',  # 直接名
    '标准Actor模型': 'Actor模型',  # 标准前缀
    'AI推理': 'AI推理',  # 直接名
    '标准AI推理': 'AI推理',  # 标准前缀
    'API文档': 'API文档',  # 直接名
    '标准API文档': 'API文档',  # 标准前缀
    'CSV': 'CSV',  # 直接名
    '标准CSV': 'CSV',  # 标准前缀
    'DNS': 'DNS',  # 直接名
    '标准DNS': 'DNS',  # 标准前缀
    'GUI框架': 'GUI框架',  # 直接名
    '标准GUI框架': 'GUI框架',  # 标准前缀
    'HTTP客户端': 'HTTP客户端',  # 直接名
    '标准HTTP客户端': 'HTTP客户端',  # 标准前缀
    'HTTP服务端': 'HTTP服务端',  # 直接名
    '标准HTTP服务端': 'HTTP服务端',  # 标准前缀
    'JSON': 'JSON',  # 直接名
    '标准JSON': 'JSON',  # 标准前缀
    'JWT': 'JWT',  # 直接名
    '标准JWT': 'JWT',  # 标准前缀
    'Markdown': 'Markdown',  # 直接名
    '标准Markdown': 'Markdown',  # 标准前缀
    'NoSQL连接器': 'NoSQL连接器',  # 直接名
    '标准NoSQL连接器': 'NoSQL连接器',  # 标准前缀
    'OAuth客户端': 'OAuth客户端',  # 直接名
    '标准OAuth客户端': 'OAuth客户端',  # 标准前缀
    'Redis绑定': 'Redis绑定',  # 直接名
    '标准Redis绑定': 'Redis绑定',  # 标准前缀
    'RPC框架': 'RPC框架',  # 直接名
    '标准RPC框架': 'RPC框架',  # 标准前缀
    'Socket': 'Socket',  # 直接名
    '标准Socket': 'Socket',  # 标准前缀
    'SQLite': 'SQLite',  # 直接名
    '标准SQLite': 'SQLite',  # 标准前缀
    'TOML': 'TOML',  # 直接名
    '标准TOML': 'TOML',  # 标准前缀
    'URL解析': 'URL解析',  # 直接名
    '标准URL解析': 'URL解析',  # 标准前缀
    'WebSocket': 'WebSocket',  # 直接名
    '标准WebSocket': 'WebSocket',  # 标准前缀
    'Web框架': 'Web框架',  # 直接名
    '标准Web框架': 'Web框架',  # 标准前缀
    'XML': 'XML',  # 直接名
    '标准XML': 'XML',  # 标准前缀
    'YAML': 'YAML',  # 直接名
    '标准YAML': 'YAML',  # 标准前缀
    '中间件集合': '中间件集合',  # 直接名
    '标准中间件集合': '中间件集合',  # 标准前缀
    '事件驱动': '事件驱动',  # 直接名
    '标准事件驱动': '事件驱动',  # 标准前缀
    '二进制编码': '二进制编码',  # 直接名
    '标准二进制编码': '二进制编码',  # 标准前缀
    '云存储': '云存储',  # 直接名
    '标准云存储': '云存储',  # 标准前缀
    '代码格式化': '代码格式化',  # 直接名
    '标准代码格式化': '代码格式化',  # 标准前缀
    '任务队列': '任务队列',  # 直接名
    '标准任务队列': '任务队列',  # 标准前缀
    '全文搜索': '全文搜索',  # 直接名
    '标准全文搜索': '全文搜索',  # 标准前缀
    '内存管理': '内存管理',  # 直接名
    '标准内存管理': '内存管理',  # 标准前缀
    '加密算法': '加密算法',  # 直接名
    '标准加密算法': '加密算法',  # 标准前缀
    '包管理增强': '包管理增强',  # 直接名
    '标准包管理增强': '包管理增强',  # 标准前缀
    '协程': '协程',  # 直接名
    '标准协程': '协程',  # 标准前缀
    '压缩算法': '压缩算法',  # 直接名
    '标准压缩算法': '压缩算法',  # 标准前缀
    '命令行参数': '命令行参数',  # 直接名
    '标准命令行参数': '命令行参数',  # 标准前缀
    '哈希': '哈希',  # 直接名
    '标准哈希': '哈希',  # 标准前缀
    '哈希算法': '哈希算法',  # 直接名
    '标准哈希算法': '哈希算法',  # 标准前缀
    '响应式编程': '响应式编程',  # 直接名
    '标准响应式编程': '响应式编程',  # 标准前缀
    '图像处理': '图像处理',  # 直接名
    '标准图像处理': '图像处理',  # 标准前缀
    '图像处理增强': '图像处理增强',  # 直接名
    '标准图像处理增强': '图像处理增强',  # 标准前缀
    '图像编解码': '图像编解码',  # 直接名
    '标准图像编解码': '图像编解码',  # 标准前缀
    '图形渲染': '图形渲染',  # 直接名
    '标准图形渲染': '图形渲染',  # 标准前缀
    '图表': '图表',  # 直接名
    '标准图表': '图表',  # 标准前缀
    '地理计算': '地理计算',  # 直接名
    '标准地理计算': '地理计算',  # 标准前缀
    '字体渲染': '字体渲染',  # 直接名
    '标准字体渲染': '字体渲染',  # 标准前缀
    '字符串处理': '字符串处理',  # 直接名
    '标准字符串处理': '字符串处理',  # 标准前缀
    '密码哈希': '密码哈希',  # 直接名
    '标准密码哈希': '密码哈希',  # 标准前缀
    '对称加密': '对称加密',  # 直接名
    '标准对称加密': '对称加密',  # 标准前缀
    '对话框': '对话框',  # 直接名
    '标准对话框': '对话框',  # 标准前缀
    '对象存储': '对象存储',  # 直接名
    '标准对象存储': '对象存储',  # 标准前缀
    '并行计算': '并行计算',  # 直接名
    '标准并行计算': '并行计算',  # 标准前缀
    '异步运行时': '异步运行时',  # 直接名
    '标准异步运行时': '异步运行时',  # 标准前缀
    '性能分析': '性能分析',  # 直接名
    '标准性能分析': '性能分析',  # 标准前缀
    '排序与搜索': '排序与搜索',  # 直接名
    '标准排序与搜索': '排序与搜索',  # 标准前缀
    '控件库': '控件库',  # 直接名
    '标准控件库': '控件库',  # 标准前缀
    '支付集成': '支付集成',  # 直接名
    '标准支付集成': '支付集成',  # 标准前缀
    '数值工具': '数值工具',  # 直接名
    '标准数值工具': '数值工具',  # 标准前缀
    '数值计算': '数值计算',  # 直接名
    '标准数值计算': '数值计算',  # 标准前缀
    '数字签名': '数字签名',  # 直接名
    '标准数字签名': '数字签名',  # 标准前缀
    '数据可视化': '数据可视化',  # 直接名
    '标准数据可视化': '数据可视化',  # 标准前缀
    '数据导入导出': '数据导入导出',  # 直接名
    '标准数据导入导出': '数据导入导出',  # 标准前缀
    '数据库迁移': '数据库迁移',  # 直接名
    '标准数据库迁移': '数据库迁移',  # 标准前缀
    '数据框': '数据框',  # 直接名
    '标准数据框': '数据框',  # 标准前缀
    '数据清洗': '数据清洗',  # 直接名
    '标准数据清洗': '数据清洗',  # 标准前缀
    '数据结构': '数据结构',  # 直接名
    '标准数据结构': '数据结构',  # 标准前缀
    '文件上传': '文件上传',  # 直接名
    '标准文件上传': '文件上传',  # 标准前缀
    '文件系统': '文件系统',  # 直接名
    '标准文件系统': '文件系统',  # 标准前缀
    '文档格式': '文档格式',  # 直接名
    '标准文档格式': '文档格式',  # 标准前缀
    '文档生成': '文档生成',  # 直接名
    '标准文档生成': '文档生成',  # 标准前缀
    '日志系统': '日志系统',  # 直接名
    '标准日志系统': '日志系统',  # 标准前缀
    '日期序列': '日期序列',  # 直接名
    '标准日期序列': '日期序列',  # 标准前缀
    '时间日期': '时间日期',  # 直接名
    '标准时间日期': '时间日期',  # 标准前缀
    '构建工具': '构建工具',  # 直接名
    '标准构建工具': '构建工具',  # 标准前缀
    '模板渲染': '模板渲染',  # 直接名
    '标准模板渲染': '模板渲染',  # 标准前缀
    '正则表达式': '正则表达式',  # 直接名
    '标准正则表达式': '正则表达式',  # 标准前缀
    '测试框架增强': '测试框架增强',  # 直接名
    '标准测试框架增强': '测试框架增强',  # 标准前缀
    '消息队列': '消息队列',  # 直接名
    '标准消息队列': '消息队列',  # 标准前缀
    '游戏引擎绑定': '游戏引擎绑定',  # 直接名
    '标准游戏引擎绑定': '游戏引擎绑定',  # 标准前缀
    '环境变量': '环境变量',  # 直接名
    '标准环境变量': '环境变量',  # 标准前缀
    '短信': '短信',  # 直接名
    '标准短信': '短信',  # 标准前缀
    '科学计算': '科学计算',  # 直接名
    '标准科学计算': '科学计算',  # 标准前缀
    '第三方登录': '第三方登录',  # 直接名
    '标准第三方登录': '第三方登录',  # 标准前缀
    '算法工具': '算法工具',  # 直接名
    '标准算法工具': '算法工具',  # 标准前缀
    '类型工具': '类型工具',  # 直接名
    '标准类型工具': '类型工具',  # 标准前缀
    '系统信息': '系统信息',  # 直接名
    '标准系统信息': '系统信息',  # 标准前缀
    '系统托盘': '系统托盘',  # 直接名
    '标准系统托盘': '系统托盘',  # 标准前缀
    '线程': '线程',  # 直接名
    '标准线程': '线程',  # 标准前缀
    '统计分析': '统计分析',  # 直接名
    '标准统计分析': '统计分析',  # 标准前缀
    '缓存系统': '缓存系统',  # 直接名
    '标准缓存系统': '缓存系统',  # 标准前缀
    '网络工具': '网络工具',  # 直接名
    '标准网络工具': '网络工具',  # 标准前缀
    '视频处理': '视频处理',  # 直接名
    '标准视频处理': '视频处理',  # 标准前缀
    '认证授权': '认证授权',  # 直接名
    '标准认证授权': '认证授权',  # 标准前缀
    '证书': '证书',  # 直接名
    '标准证书': '证书',  # 标准前缀
    '请求验证': '请求验证',  # 直接名
    '标准请求验证': '请求验证',  # 标准前缀
    '调试器': '调试器',  # 直接名
    '标准调试器': '调试器',  # 标准前缀
    '路径处理': '路径处理',  # 直接名
    '标准路径处理': '路径处理',  # 标准前缀
    '路由': '路由',  # 直接名
    '标准路由': '路由',  # 标准前缀
    '进程管理': '进程管理',  # 直接名
    '标准进程管理': '进程管理',  # 标准前缀
    '连接池': '连接池',  # 直接名
    '标准连接池': '连接池',  # 标准前缀
    '迭代器工具': '迭代器工具',  # 直接名
    '标准迭代器工具': '迭代器工具',  # 标准前缀
    '邮件': '邮件',  # 直接名
    '标准邮件': '邮件',  # 标准前缀
    '错误处理': '错误处理',  # 直接名
    '标准错误处理': '错误处理',  # 标准前缀
    '随机数': '随机数',  # 直接名
    '标准随机数': '随机数',  # 标准前缀
    '集合扩展': '集合扩展',  # 直接名
    '标准集合扩展': '集合扩展',  # 标准前缀
    '静态分析': '静态分析',  # 直接名
    '标准静态分析': '静态分析',  # 标准前缀
    '非对称加密': '非对称加密',  # 直接名
    '标准非对称加密': '非对称加密',  # 标准前缀
    '音频处理': '音频处理',  # 直接名
    '标准音频处理': '音频处理',  # 标准前缀
}

# 统计: 109 包, 2721 公开函数, 642 FFI 声明
TOTAL_PACKAGES = 109
TOTAL_FUNCTIONS = 2721
TOTAL_FFI = 642
